-- ==============================================================================
-- PART 1/4: ENUMS, TABLES, INDEXES, HELPER FUNCTIONS
-- ==============================================================================
-- Run this FIRST on a fresh Supabase instance.
-- Safe to re-run: uses IF NOT EXISTS / CREATE OR REPLACE / DROP IF EXISTS.
-- ==============================================================================


-- ==============================================================================
-- SECTION 1: ENUMS
-- ==============================================================================

DO $$ BEGIN
    CREATE TYPE public.leave_request_type AS ENUM ('CONGE', 'RECUPERATION');
EXCEPTION WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE public.leave_status AS ENUM (
        'PENDING',
        'VALIDATED_DC',
        'VALIDATED_RP',
        'VALIDATED_TG',
        'VALIDATED_DE',
        'APPROVED',
        'REJECTED',
        'CANCELLED',
        'ARCHIVED'
    );
EXCEPTION WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE public.user_role AS ENUM (
        'EMPLOYEE',
        'CHEF_SERVICE',
        'RH',
        'TRESORIER_GENERAL',
        'DIRECTEUR_EXECUTIF',
        'ADMIN'
    );
EXCEPTION WHEN duplicate_object THEN null;
END $$;


-- ==============================================================================
-- SECTION 2: CORE TABLES
-- ==============================================================================

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- Companies
CREATE TABLE IF NOT EXISTS public.companies (
    id bigint generated by default as identity primary key,
    legacy_id text UNIQUE,
    name text NOT NULL UNIQUE,
    created_at timestamptz default now() not null,
    updated_at timestamptz default now() not null
);

-- Departments
CREATE TABLE IF NOT EXISTS public.departments (
    id bigint generated by default as identity primary key,
    legacy_id bigint UNIQUE,
    name text NOT NULL,
    company_id bigint references public.companies(id) ON DELETE CASCADE,
    filter_budget text,
    filter_article text,
    created_at timestamptz default now() not null,
    updated_at timestamptz default now() not null
);

-- Utilisateurs (standalone, no auth.users dependency for table creation)
CREATE TABLE IF NOT EXISTS public.utilisateurs (
    id uuid default gen_random_uuid() primary key,
    legacy_id bigint UNIQUE,
    email text UNIQUE,
    password_hash text,
    full_name text NOT NULL,
    username text UNIQUE,
    company_id bigint references public.companies(id),
    department_id bigint references public.departments(id),
    job_title text,
    role public.user_role default 'EMPLOYEE',
    is_active boolean default true,
    balance_conge float default 0,
    balance_recuperation float default 0,
    phone text,
    avatar_url text,
    hire_date date,
    birth_date date,
    matricule text,
    cin text,
    cnss text,
    rib text,
    address text,
    city text,
    gender text,
    legacy_profile_id int,
    is_signatory boolean default false,
    signatory_type text,
    signature_file text,
    last_login timestamptz,
    created_at timestamptz default now() not null,
    updated_at timestamptz default now() not null
);

-- Leave requests
CREATE TABLE IF NOT EXISTS public.leave_requests (
    id bigint generated by default as identity primary key,
    legacy_id bigint UNIQUE,
    user_id uuid references public.utilisateurs(id) NOT NULL,
    created_by uuid,
    request_type public.leave_request_type NOT NULL,
    start_date date NOT NULL,
    end_date date NOT NULL,
    days_count float NOT NULL,
    return_date date,
    replacement_user_id uuid references public.utilisateurs(id),
    status public.leave_status default 'PENDING',
    initial_status public.leave_status,
    reason text,
    comments text,
    balance_before float,
    balance_conge_used float,
    balance_recuperation_used float,
    approved_by_dc uuid references public.utilisateurs(id),
    approved_by_rp uuid references public.utilisateurs(id),
    approved_by_tg uuid references public.utilisateurs(id),
    approved_by_de uuid references public.utilisateurs(id),
    approved_at_dc timestamptz,
    approved_at_rp timestamptz,
    approved_at_tg timestamptz,
    approved_at_de timestamptz,
    rejected_by uuid references public.utilisateurs(id),
    rejected_at timestamptz,
    rejection_reason text,
    created_at timestamptz default now() not null,
    updated_at timestamptz default now() not null
);

-- Ensure columns exist on older schemas (IF NOT EXISTS = safe to re-run)
ALTER TABLE public.leave_requests ADD COLUMN IF NOT EXISTS created_by uuid;
ALTER TABLE public.leave_requests ADD COLUMN IF NOT EXISTS initial_status public.leave_status;
ALTER TABLE public.leave_requests ADD COLUMN IF NOT EXISTS balance_before float;
ALTER TABLE public.leave_requests ADD COLUMN IF NOT EXISTS balance_conge_used float;
ALTER TABLE public.leave_requests ADD COLUMN IF NOT EXISTS balance_recuperation_used float;

-- Mission requests (Ordre de Mission)
CREATE TABLE IF NOT EXISTS public.mission_requests (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid REFERENCES public.utilisateurs(id) NOT NULL,
    assigned_by uuid REFERENCES public.utilisateurs(id),
    created_by uuid,
    request_origin TEXT NOT NULL DEFAULT 'SELF',
    mission_scope TEXT NOT NULL DEFAULT 'LOCAL',
    departure_city TEXT NOT NULL,
    arrival_city TEXT NOT NULL,
    mission_object TEXT NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    days_count FLOAT NOT NULL,
    transport_type TEXT,
    transport_details TEXT,
    replacement_user_id uuid REFERENCES public.utilisateurs(id),
    comments TEXT,
    status public.leave_status DEFAULT 'PENDING',
    initial_status public.leave_status,
    supervisor_opinion TEXT,
    supervisor_comments TEXT,
    supervisor_id uuid REFERENCES public.utilisateurs(id),
    supervisor_at TIMESTAMPTZ,
    approved_by_dc uuid REFERENCES public.utilisateurs(id),
    approved_by_rp uuid REFERENCES public.utilisateurs(id),
    approved_by_tg uuid REFERENCES public.utilisateurs(id),
    approved_by_de uuid REFERENCES public.utilisateurs(id),
    approved_at_dc TIMESTAMPTZ,
    approved_at_rp TIMESTAMPTZ,
    approved_at_tg TIMESTAMPTZ,
    approved_at_de TIMESTAMPTZ,
    director_decision TEXT,
    rejected_by uuid REFERENCES public.utilisateurs(id),
    rejected_at TIMESTAMPTZ,
    rejection_reason TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Ensure columns exist on older schemas
ALTER TABLE public.mission_requests ADD COLUMN IF NOT EXISTS created_by uuid;
ALTER TABLE public.mission_requests ADD COLUMN IF NOT EXISTS initial_status public.leave_status;

-- Leave balance history
CREATE TABLE IF NOT EXISTS public.leave_balance_history (
    id bigint generated by default as identity primary key,
    user_id uuid references public.utilisateurs(id) NOT NULL,
    type public.leave_request_type NOT NULL,
    amount float NOT NULL,
    reason text,
    year int,
    date_from date,
    date_to date,
    created_at timestamptz default now() not null
);

-- Working days configuration
CREATE TABLE IF NOT EXISTS public.working_days (
    id bigint generated by default as identity primary key,
    company_id bigint references public.companies(id),
    monday boolean default true,
    tuesday boolean default true,
    wednesday boolean default true,
    thursday boolean default true,
    friday boolean default true,
    saturday boolean default false,
    sunday boolean default false
);

-- Holidays
CREATE TABLE IF NOT EXISTS public.holidays (
    id bigint generated by default as identity primary key,
    company_id bigint references public.companies(id),
    name text NOT NULL,
    date date NOT NULL,
    is_recurring boolean default false,
    created_at timestamptz default now() not null
);

-- Notifications
CREATE TABLE IF NOT EXISTS public.notifications (
    id bigint generated by default as identity primary key,
    user_id uuid references public.utilisateurs(id) NOT NULL,
    title text NOT NULL,
    message text NOT NULL,
    type text,
    related_request_id bigint references public.leave_requests(id),
    is_read boolean default false,
    created_at timestamptz default now() not null
);

-- Audit logs
CREATE TABLE IF NOT EXISTS public.audit_logs (
    id bigint generated by default as identity primary key,
    table_name text NOT NULL,
    record_id bigint,
    action text NOT NULL,
    old_data jsonb,
    new_data jsonb,
    user_id uuid references public.utilisateurs(id),
    created_at timestamptz default now() not null
);


-- ==============================================================================
-- SECTION 3: INDEXES
-- ==============================================================================

CREATE INDEX IF NOT EXISTS idx_utilisateurs_company ON public.utilisateurs(company_id);
CREATE INDEX IF NOT EXISTS idx_utilisateurs_department ON public.utilisateurs(department_id);
CREATE INDEX IF NOT EXISTS idx_utilisateurs_role ON public.utilisateurs(role);
CREATE INDEX IF NOT EXISTS idx_utilisateurs_legacy_id ON public.utilisateurs(legacy_id);
CREATE INDEX IF NOT EXISTS idx_utilisateurs_email ON public.utilisateurs(email);
CREATE INDEX IF NOT EXISTS idx_leave_requests_user ON public.leave_requests(user_id);
CREATE INDEX IF NOT EXISTS idx_leave_requests_status ON public.leave_requests(status);
CREATE INDEX IF NOT EXISTS idx_leave_requests_dates ON public.leave_requests(start_date, end_date);
CREATE INDEX IF NOT EXISTS idx_notifications_user ON public.notifications(user_id, is_read);
CREATE INDEX IF NOT EXISTS idx_departments_legacy_id ON public.departments(legacy_id);
CREATE INDEX IF NOT EXISTS idx_mission_requests_user ON public.mission_requests(user_id);
CREATE INDEX IF NOT EXISTS idx_mission_requests_assigned_by ON public.mission_requests(assigned_by);
CREATE INDEX IF NOT EXISTS idx_mission_requests_status ON public.mission_requests(status);
CREATE INDEX IF NOT EXISTS idx_mission_requests_dates ON public.mission_requests(start_date, end_date);


-- ==============================================================================
-- SECTION 4: HELPER FUNCTIONS
-- ==============================================================================

-- Drop old versions first
DROP FUNCTION IF EXISTS public.get_my_role() CASCADE;
DROP FUNCTION IF EXISTS public.is_manager() CASCADE;
DROP FUNCTION IF EXISTS public.can_manage_user(UUID) CASCADE;

-- Get current user's role
CREATE OR REPLACE FUNCTION public.get_my_role()
RETURNS TEXT
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT role::TEXT FROM public.utilisateurs WHERE id = auth.uid();
$$;

-- Check if current user is a manager
CREATE OR REPLACE FUNCTION public.is_manager()
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT role::TEXT IN ('CHEF_SERVICE', 'RH', 'DIRECTEUR_EXECUTIF', 'ADMIN')
  FROM public.utilisateurs
  WHERE id = auth.uid();
$$;

-- Department-scoped management check
-- CHEF_SERVICE -> same department only
-- RESPONSABLE_PERSONNEL / DIRECTEUR_EXECUTIF / ADMIN -> full cross-department access
CREATE OR REPLACE FUNCTION public.can_manage_user(target_user_id UUID)
RETURNS boolean
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_role       TEXT;
  v_dept_id    BIGINT;
  v_target_dept BIGINT;
BEGIN
  SELECT role::TEXT, department_id
  INTO v_role, v_dept_id
  FROM public.utilisateurs
  WHERE id = auth.uid();

  IF NOT FOUND THEN
    RETURN FALSE;
  END IF;

  -- Global roles: full access
  IF v_role IN ('RH', 'DIRECTEUR_EXECUTIF', 'ADMIN') THEN
    RETURN TRUE;
  END IF;

  -- CHEF_SERVICE: same department only
  IF v_role = 'CHEF_SERVICE' AND v_dept_id IS NOT NULL THEN
    SELECT department_id INTO v_target_dept
    FROM public.utilisateurs
    WHERE id = target_user_id;

    RETURN v_dept_id = v_target_dept;
  END IF;

  RETURN FALSE;
END;
$$;
