-- ==============================================================================
-- PART 5: NEW CLIENT FEATURES (Requirements 1-12)
-- ==============================================================================
-- Run AFTER 04_grants_seed.sql.
-- Safe to re-run: uses IF NOT EXISTS / CREATE OR REPLACE / DROP IF EXISTS.
-- ==============================================================================


-- ==============================================================================
-- REQ #1, #2, #3: PERSONNEL CATEGORIES + HALF-DAY WORKING DAYS + ANNUAL DAYS
-- ==============================================================================

-- Personnel categories (links employees to configurable working days & annual leave)
CREATE TABLE IF NOT EXISTS public.personnel_categories (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id bigint REFERENCES public.companies(id) ON DELETE CASCADE,
    name text NOT NULL,
    description text,
    annual_leave_days float NOT NULL DEFAULT 18,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_at timestamptz DEFAULT now() NOT NULL,
    UNIQUE(company_id, name)
);

-- Add category_id to utilisateurs
ALTER TABLE public.utilisateurs ADD COLUMN IF NOT EXISTS category_id bigint REFERENCES public.personnel_categories(id);
CREATE INDEX IF NOT EXISTS idx_utilisateurs_category ON public.utilisateurs(category_id);

-- Add category_id to working_days (per-category working days config)
ALTER TABLE public.working_days ADD COLUMN IF NOT EXISTS category_id bigint REFERENCES public.personnel_categories(id);

-- Half-day columns for working_days (Req #2)
ALTER TABLE public.working_days ADD COLUMN IF NOT EXISTS monday_morning boolean DEFAULT true;
ALTER TABLE public.working_days ADD COLUMN IF NOT EXISTS monday_afternoon boolean DEFAULT true;
ALTER TABLE public.working_days ADD COLUMN IF NOT EXISTS tuesday_morning boolean DEFAULT true;
ALTER TABLE public.working_days ADD COLUMN IF NOT EXISTS tuesday_afternoon boolean DEFAULT true;
ALTER TABLE public.working_days ADD COLUMN IF NOT EXISTS wednesday_morning boolean DEFAULT true;
ALTER TABLE public.working_days ADD COLUMN IF NOT EXISTS wednesday_afternoon boolean DEFAULT true;
ALTER TABLE public.working_days ADD COLUMN IF NOT EXISTS thursday_morning boolean DEFAULT true;
ALTER TABLE public.working_days ADD COLUMN IF NOT EXISTS thursday_afternoon boolean DEFAULT true;
ALTER TABLE public.working_days ADD COLUMN IF NOT EXISTS friday_morning boolean DEFAULT true;
ALTER TABLE public.working_days ADD COLUMN IF NOT EXISTS friday_afternoon boolean DEFAULT true;
ALTER TABLE public.working_days ADD COLUMN IF NOT EXISTS saturday_morning boolean DEFAULT true;
ALTER TABLE public.working_days ADD COLUMN IF NOT EXISTS saturday_afternoon boolean DEFAULT false;
ALTER TABLE public.working_days ADD COLUMN IF NOT EXISTS sunday_morning boolean DEFAULT false;
ALTER TABLE public.working_days ADD COLUMN IF NOT EXISTS sunday_afternoon boolean DEFAULT false;

-- Half-day selection on leave requests (Req #2)
ALTER TABLE public.leave_requests ADD COLUMN IF NOT EXISTS start_half_day text DEFAULT 'FULL';
ALTER TABLE public.leave_requests ADD COLUMN IF NOT EXISTS end_half_day text DEFAULT 'FULL';


-- ==============================================================================
-- REQ #5: MONTHLY BALANCE ACCRUAL TRACKING
-- ==============================================================================

CREATE TABLE IF NOT EXISTS public.monthly_balance_accrual (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid REFERENCES public.utilisateurs(id) NOT NULL,
    year int NOT NULL,
    month int NOT NULL,
    accrued_days float NOT NULL,
    cumulative_days float NOT NULL,
    annual_entitlement float NOT NULL,
    created_at timestamptz DEFAULT now() NOT NULL,
    UNIQUE(user_id, year, month)
);

CREATE INDEX IF NOT EXISTS idx_monthly_accrual_user_year ON public.monthly_balance_accrual(user_id, year);


-- ==============================================================================
-- REQ #8: RECOVERY REQUESTS (VALIDATION WORKFLOW)
-- ==============================================================================

DO $$ BEGIN
    CREATE TYPE public.recovery_work_type AS ENUM (
        'JOUR_FERIE',
        'JOUR_REPOS',
        'SAMEDI',
        'DIMANCHE'
    );
EXCEPTION WHEN duplicate_object THEN null;
END $$;

CREATE TABLE IF NOT EXISTS public.recovery_requests (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid REFERENCES public.utilisateurs(id) NOT NULL,
    days float NOT NULL,
    date_worked date NOT NULL,
    work_type public.recovery_work_type NOT NULL,
    period text DEFAULT 'FULL' CHECK (period IN ('MORNING', 'AFTERNOON', 'FULL')),
    reason text,
    status text DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'VALIDATED', 'REJECTED')),
    validated_by uuid REFERENCES public.utilisateurs(id),
    validated_at timestamptz,
    rejection_reason text,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_at timestamptz DEFAULT now() NOT NULL
);

-- Add period column if table already exists
ALTER TABLE public.recovery_requests ADD COLUMN IF NOT EXISTS period text DEFAULT 'FULL' CHECK (period IN ('MORNING', 'AFTERNOON', 'FULL'));

CREATE INDEX IF NOT EXISTS idx_recovery_requests_user ON public.recovery_requests(user_id);
CREATE INDEX IF NOT EXISTS idx_recovery_requests_status ON public.recovery_requests(status);


-- ==============================================================================
-- REQ #9: COMBINED LEAVE+RECOVERY REQUESTS (LEAVE REQUEST DETAILS)
-- ==============================================================================

CREATE TABLE IF NOT EXISTS public.leave_request_details (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id bigint REFERENCES public.leave_requests(id) ON DELETE CASCADE NOT NULL,
    date date NOT NULL,
    type text NOT NULL CHECK (type IN ('CONGE', 'RECUPERATION')),
    half_day text DEFAULT 'FULL' CHECK (half_day IN ('FULL', 'MORNING', 'AFTERNOON')),
    UNIQUE(request_id, date)
);

CREATE INDEX IF NOT EXISTS idx_leave_request_details_request ON public.leave_request_details(request_id);

-- Allow mixed-type requests
ALTER TABLE public.leave_requests ADD COLUMN IF NOT EXISTS is_mixed boolean DEFAULT false;


-- ==============================================================================
-- REQ #10: RECOVERY EXPIRATION (30 JUNE N+1)
-- ==============================================================================

ALTER TABLE public.leave_balance_history ADD COLUMN IF NOT EXISTS expires_at date;

-- Track recovery balances with expiration
CREATE TABLE IF NOT EXISTS public.recovery_balance_lots (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid REFERENCES public.utilisateurs(id) NOT NULL,
    days float NOT NULL,
    remaining_days float NOT NULL,
    year_acquired int NOT NULL,
    expires_at date NOT NULL,
    expired boolean DEFAULT false,
    source_request_id bigint REFERENCES public.recovery_requests(id),
    created_at timestamptz DEFAULT now() NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_recovery_lots_user ON public.recovery_balance_lots(user_id, expired);


-- ==============================================================================
-- REQ #12: MULTI-COMPANY MULTI-PROFILE
-- ==============================================================================

CREATE TABLE IF NOT EXISTS public.user_company_roles (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid REFERENCES public.utilisateurs(id) ON DELETE CASCADE NOT NULL,
    company_id bigint REFERENCES public.companies(id) ON DELETE CASCADE NOT NULL,
    role public.user_role DEFAULT 'EMPLOYEE',
    is_active boolean DEFAULT true,
    created_at timestamptz DEFAULT now() NOT NULL,
    UNIQUE(user_id, company_id)
);

CREATE INDEX IF NOT EXISTS idx_user_company_roles_user ON public.user_company_roles(user_id);
CREATE INDEX IF NOT EXISTS idx_user_company_roles_company ON public.user_company_roles(company_id);


-- ==============================================================================
-- RLS POLICIES FOR NEW TABLES
-- ==============================================================================

-- Personnel Categories
ALTER TABLE public.personnel_categories ENABLE ROW LEVEL SECURITY;

CREATE POLICY "personnel_categories_select"
  ON public.personnel_categories FOR SELECT TO authenticated USING (true);

CREATE POLICY "personnel_categories_manage"
  ON public.personnel_categories FOR ALL TO authenticated
  USING (public.is_manager())
  WITH CHECK (public.is_manager());

-- Monthly Balance Accrual
ALTER TABLE public.monthly_balance_accrual ENABLE ROW LEVEL SECURITY;

CREATE POLICY "monthly_accrual_select"
  ON public.monthly_balance_accrual FOR SELECT TO authenticated
  USING (user_id = auth.uid() OR public.can_manage_user(user_id));

CREATE POLICY "monthly_accrual_manage"
  ON public.monthly_balance_accrual FOR ALL TO authenticated
  USING (public.is_manager())
  WITH CHECK (public.is_manager());

-- Recovery Requests
ALTER TABLE public.recovery_requests ENABLE ROW LEVEL SECURITY;

CREATE POLICY "recovery_requests_select"
  ON public.recovery_requests FOR SELECT TO authenticated
  USING (user_id = auth.uid() OR public.can_manage_user(user_id));

CREATE POLICY "recovery_requests_insert"
  ON public.recovery_requests FOR INSERT TO authenticated
  WITH CHECK (user_id = auth.uid());

CREATE POLICY "recovery_requests_update_manager"
  ON public.recovery_requests FOR UPDATE TO authenticated
  USING (public.can_manage_user(user_id));

-- Leave Request Details
ALTER TABLE public.leave_request_details ENABLE ROW LEVEL SECURITY;

CREATE POLICY "leave_request_details_select"
  ON public.leave_request_details FOR SELECT TO authenticated USING (true);

CREATE POLICY "leave_request_details_insert"
  ON public.leave_request_details FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "leave_request_details_delete"
  ON public.leave_request_details FOR DELETE TO authenticated
  USING (public.is_manager() OR EXISTS (
    SELECT 1 FROM public.leave_requests lr
    WHERE lr.id = request_id AND lr.user_id = auth.uid() AND lr.status = 'PENDING'
  ));

-- Recovery Balance Lots
ALTER TABLE public.recovery_balance_lots ENABLE ROW LEVEL SECURITY;

CREATE POLICY "recovery_lots_select"
  ON public.recovery_balance_lots FOR SELECT TO authenticated
  USING (user_id = auth.uid() OR public.can_manage_user(user_id));

CREATE POLICY "recovery_lots_manage"
  ON public.recovery_balance_lots FOR ALL TO authenticated
  USING (public.is_manager())
  WITH CHECK (public.is_manager());

-- User Company Roles
ALTER TABLE public.user_company_roles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "user_company_roles_select"
  ON public.user_company_roles FOR SELECT TO authenticated USING (true);

CREATE POLICY "user_company_roles_manage"
  ON public.user_company_roles FOR ALL TO authenticated
  USING (public.get_my_role() = 'ADMIN')
  WITH CHECK (public.get_my_role() = 'ADMIN');


-- ==============================================================================
-- NEW AND UPDATED RPCs
-- ==============================================================================

-- ── REQ #1: Updated count_working_days with category support ──
CREATE OR REPLACE FUNCTION count_working_days(
  p_start_date DATE,
  p_end_date   DATE,
  p_company_id BIGINT DEFAULT NULL,
  p_category_id BIGINT DEFAULT NULL,
  p_start_half_day TEXT DEFAULT 'FULL',
  p_end_half_day TEXT DEFAULT 'FULL'
)
RETURNS FLOAT
LANGUAGE plpgsql
STABLE
AS $$
DECLARE
  v_count      FLOAT := 0;
  v_current    DATE := p_start_date;
  v_dow        INTEGER;
  v_company    BIGINT;
  v_is_holiday BOOLEAN;
  v_wd         RECORD;
  v_day_active BOOLEAN;
  v_morning    BOOLEAN;
  v_afternoon  BOOLEAN;
  v_day_value  FLOAT;
BEGIN
  v_company := COALESCE(p_company_id, (SELECT id FROM public.companies LIMIT 1));

  -- Try category-specific working days first, fall back to company-level
  IF p_category_id IS NOT NULL THEN
    SELECT * INTO v_wd FROM public.working_days WHERE category_id = p_category_id LIMIT 1;
  END IF;

  IF NOT FOUND OR p_category_id IS NULL THEN
    SELECT * INTO v_wd FROM public.working_days WHERE company_id = v_company AND category_id IS NULL LIMIT 1;
  END IF;

  IF NOT FOUND THEN
    -- Default fallback: Mon-Sat full days
    v_wd.monday := true; v_wd.tuesday := true; v_wd.wednesday := true;
    v_wd.thursday := true; v_wd.friday := true; v_wd.saturday := true; v_wd.sunday := false;
    v_wd.monday_morning := true; v_wd.monday_afternoon := true;
    v_wd.tuesday_morning := true; v_wd.tuesday_afternoon := true;
    v_wd.wednesday_morning := true; v_wd.wednesday_afternoon := true;
    v_wd.thursday_morning := true; v_wd.thursday_afternoon := true;
    v_wd.friday_morning := true; v_wd.friday_afternoon := true;
    v_wd.saturday_morning := true; v_wd.saturday_afternoon := false;
    v_wd.sunday_morning := false; v_wd.sunday_afternoon := false;
  END IF;

  WHILE v_current <= p_end_date LOOP
    v_dow := EXTRACT(ISODOW FROM v_current)::INTEGER;

    -- Check if the full day is active (legacy boolean)
    v_day_active := CASE v_dow
      WHEN 1 THEN v_wd.monday
      WHEN 2 THEN v_wd.tuesday
      WHEN 3 THEN v_wd.wednesday
      WHEN 4 THEN v_wd.thursday
      WHEN 5 THEN v_wd.friday
      WHEN 6 THEN v_wd.saturday
      WHEN 7 THEN v_wd.sunday
      ELSE false
    END;

    IF v_day_active THEN
      -- Check holiday
      SELECT EXISTS(
        SELECT 1 FROM public.holidays h
        WHERE h.company_id = v_company
        AND (
          (h.is_recurring = true
           AND EXTRACT(MONTH FROM h.date) = EXTRACT(MONTH FROM v_current)
           AND EXTRACT(DAY FROM h.date) = EXTRACT(DAY FROM v_current))
          OR
          (h.is_recurring = false AND h.date = v_current)
        )
      ) INTO v_is_holiday;

      IF NOT v_is_holiday THEN
        -- Check half-day configuration
        v_morning := COALESCE(CASE v_dow
          WHEN 1 THEN v_wd.monday_morning
          WHEN 2 THEN v_wd.tuesday_morning
          WHEN 3 THEN v_wd.wednesday_morning
          WHEN 4 THEN v_wd.thursday_morning
          WHEN 5 THEN v_wd.friday_morning
          WHEN 6 THEN v_wd.saturday_morning
          WHEN 7 THEN v_wd.sunday_morning
        END, true);

        v_afternoon := COALESCE(CASE v_dow
          WHEN 1 THEN v_wd.monday_afternoon
          WHEN 2 THEN v_wd.tuesday_afternoon
          WHEN 3 THEN v_wd.wednesday_afternoon
          WHEN 4 THEN v_wd.thursday_afternoon
          WHEN 5 THEN v_wd.friday_afternoon
          WHEN 6 THEN v_wd.saturday_afternoon
          WHEN 7 THEN v_wd.sunday_afternoon
        END, false);

        -- Calculate day value based on which half-days are worked
        v_day_value := 0;
        IF v_morning THEN v_day_value := v_day_value + 0.5; END IF;
        IF v_afternoon THEN v_day_value := v_day_value + 0.5; END IF;

        -- Apply start/end half-day restrictions
        IF v_current = p_start_date AND p_start_half_day = 'AFTERNOON' AND v_morning THEN
          v_day_value := v_day_value - 0.5;
        END IF;
        IF v_current = p_end_date AND p_end_half_day = 'MORNING' AND v_afternoon THEN
          v_day_value := v_day_value - 0.5;
        END IF;

        v_count := v_count + GREATEST(v_day_value, 0);
      END IF;
    END IF;

    v_current := v_current + 1;
  END LOOP;

  RETURN v_count;
END;
$$;


-- ── REQ #3: Updated calculate_annual_entitlement with category-based days ──
CREATE OR REPLACE FUNCTION calculate_annual_entitlement(p_user_id UUID)
RETURNS JSONB
LANGUAGE plpgsql
STABLE
AS $$
DECLARE
  v_user              utilisateurs%ROWTYPE;
  v_category          personnel_categories%ROWTYPE;
  v_hire_date         DATE;
  v_years_of_service  FLOAT;
  v_seniority_periods INTEGER;
  v_base_days         FLOAT := 18.0;
  v_bonus_days        FLOAT := 0;
  v_total_entitlement FLOAT;
  v_max_days          FLOAT := 30.0;
  v_is_minor          BOOLEAN := false;
BEGIN
  SELECT * INTO v_user FROM utilisateurs WHERE id = p_user_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'User % not found', p_user_id;
  END IF;

  -- Use category-specific annual leave days if available
  IF v_user.category_id IS NOT NULL THEN
    SELECT * INTO v_category FROM personnel_categories WHERE id = v_user.category_id;
    IF FOUND AND v_category.annual_leave_days IS NOT NULL THEN
      v_base_days := v_category.annual_leave_days;
    END IF;
  END IF;

  v_hire_date := COALESCE(v_user.hire_date, CURRENT_DATE);

  IF v_user.birth_date IS NOT NULL THEN
    v_is_minor := (age(CURRENT_DATE, v_user.birth_date) < interval '18 years');
  END IF;

  IF v_is_minor THEN
    v_base_days := GREATEST(v_base_days, 24.0);
  END IF;

  v_years_of_service := EXTRACT(EPOCH FROM age(CURRENT_DATE, v_hire_date)) / (365.25 * 86400);
  v_seniority_periods := FLOOR(v_years_of_service / 5.0)::INTEGER;
  v_bonus_days := v_seniority_periods * 1.5;
  v_total_entitlement := LEAST(v_base_days + v_bonus_days, v_max_days);

  RETURN jsonb_build_object(
    'user_id',            p_user_id,
    'hire_date',          v_hire_date,
    'years_of_service',   ROUND(v_years_of_service::NUMERIC, 1),
    'seniority_periods',  v_seniority_periods,
    'base_days',          v_base_days,
    'bonus_days',         v_bonus_days,
    'annual_entitlement', v_total_entitlement,
    'is_minor',           v_is_minor,
    'max_days',           v_max_days,
    'category_id',        v_user.category_id
  );
END;
$$;


-- ── REQ #5: Monthly balance accrual ──
CREATE OR REPLACE FUNCTION accrue_monthly_balance(
  p_year INT DEFAULT NULL,
  p_month INT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_user         RECORD;
  v_entitlement  JSONB;
  v_annual       FLOAT;
  v_monthly      FLOAT;
  v_cumulative   FLOAT;
  v_year         INT := COALESCE(p_year, EXTRACT(YEAR FROM CURRENT_DATE)::INT);
  v_month        INT := COALESCE(p_month, EXTRACT(MONTH FROM CURRENT_DATE)::INT);
  v_count        INT := 0;
  v_max_balance  FLOAT := 52.0;
BEGIN
  FOR v_user IN SELECT id FROM utilisateurs WHERE is_active = true LOOP
    v_entitlement := calculate_annual_entitlement(v_user.id);
    v_annual := (v_entitlement->>'annual_entitlement')::FLOAT;
    v_monthly := ROUND((v_annual / 12.0)::NUMERIC, 2)::FLOAT;

    -- Get previous cumulative
    SELECT COALESCE(cumulative_days, 0) INTO v_cumulative
    FROM monthly_balance_accrual
    WHERE user_id = v_user.id AND year = v_year AND month = v_month - 1;

    IF NOT FOUND THEN
      IF v_month = 1 THEN
        v_cumulative := 0;
      ELSE
        v_cumulative := v_monthly * (v_month - 1);
      END IF;
    END IF;

    v_cumulative := v_cumulative + v_monthly;

    -- Insert or update (audit trail only — balance_conge is managed by RH via Init. Soldes)
    INSERT INTO monthly_balance_accrual (user_id, year, month, accrued_days, cumulative_days, annual_entitlement)
    VALUES (v_user.id, v_year, v_month, v_monthly, v_cumulative, v_annual)
    ON CONFLICT (user_id, year, month)
    DO UPDATE SET accrued_days = EXCLUDED.accrued_days,
                  cumulative_days = EXCLUDED.cumulative_days,
                  annual_entitlement = EXCLUDED.annual_entitlement;

    -- NOTE: We do NOT update utilisateurs.balance_conge here.
    -- The RH sets the annual total via Init. Soldes.
    -- The frontend calculates monthly available as: balance_conge / 12 * current_month

    v_count := v_count + 1;
  END LOOP;

  RETURN jsonb_build_object(
    'employees_processed', v_count,
    'year', v_year,
    'month', v_month,
    'status', 'completed'
  );
END;
$$;


-- ── REQ #7: Updated set_initial_balance with 52-day cap ──
CREATE OR REPLACE FUNCTION set_initial_balance(
  p_user_id  UUID,
  p_balance  FLOAT,
  p_year     INTEGER,
  p_reason   TEXT DEFAULT 'Initialisation solde par RH'
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_user        utilisateurs%ROWTYPE;
  v_old_balance FLOAT;
  v_max_balance FLOAT := 52.0;
  v_capped      BOOLEAN := false;
  v_final_balance FLOAT;
BEGIN
  SELECT * INTO v_user FROM utilisateurs WHERE id = p_user_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Utilisateur % introuvable', p_user_id;
  END IF;

  IF p_balance < 0 THEN
    RAISE EXCEPTION 'Le solde ne peut pas etre negatif';
  END IF;

  v_old_balance := v_user.balance_conge;

  -- Cap at 52 days (Req #7)
  IF p_balance > v_max_balance THEN
    v_final_balance := v_max_balance;
    v_capped := true;
  ELSE
    v_final_balance := p_balance;
  END IF;

  UPDATE utilisateurs
  SET balance_conge = v_final_balance, updated_at = NOW()
  WHERE id = p_user_id;

  INSERT INTO leave_balance_history (user_id, type, amount, reason, year)
  VALUES (
    p_user_id,
    'CONGE',
    v_final_balance,
    COALESCE(p_reason, 'Initialisation solde par RH') || ' (ancien solde: ' || v_old_balance || ')',
    p_year
  );

  RETURN jsonb_build_object(
    'user_id',     p_user_id,
    'old_balance', v_old_balance,
    'new_balance', v_final_balance,
    'year',        p_year,
    'capped',      v_capped,
    'max_balance', v_max_balance
  );
END;
$$;


-- ── REQ #7: Updated calculate_leave_balance with cap info ──
CREATE OR REPLACE FUNCTION calculate_leave_balance(p_user_id UUID)
RETURNS JSONB
LANGUAGE plpgsql
STABLE
AS $$
DECLARE
  v_user                utilisateurs%ROWTYPE;
  v_entitlement         JSONB;
  v_annual_entitlement  FLOAT;
  v_current_year        INTEGER := EXTRACT(YEAR FROM CURRENT_DATE)::INTEGER;
  v_current_month       INTEGER := EXTRACT(MONTH FROM CURRENT_DATE)::INTEGER;
  v_days_used_this_year FLOAT := 0;
  v_days_pending        FLOAT := 0;
  v_recup_used          FLOAT := 0;
  v_recup_pending       FLOAT := 0;
  v_monthly_accrued     FLOAT := 0;
  v_max_balance         FLOAT := 52.0;
  v_is_max_reached      BOOLEAN := false;
  v_recup_expires_at    DATE;
BEGIN
  SELECT * INTO v_user FROM utilisateurs WHERE id = p_user_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'User % not found', p_user_id;
  END IF;

  v_entitlement := calculate_annual_entitlement(p_user_id);
  v_annual_entitlement := (v_entitlement->>'annual_entitlement')::FLOAT;

  SELECT COALESCE(SUM(days_count), 0) INTO v_days_used_this_year
  FROM leave_requests
  WHERE user_id = p_user_id
    AND request_type = 'CONGE'
    AND status = 'APPROVED'
    AND EXTRACT(YEAR FROM start_date) = v_current_year;

  SELECT COALESCE(SUM(days_count), 0) INTO v_days_pending
  FROM leave_requests
  WHERE user_id = p_user_id
    AND request_type = 'CONGE'
    AND status IN ('PENDING', 'VALIDATED_RP', 'VALIDATED_DC')
    AND EXTRACT(YEAR FROM start_date) = v_current_year;

  SELECT COALESCE(SUM(days_count), 0) INTO v_recup_used
  FROM leave_requests
  WHERE user_id = p_user_id
    AND request_type = 'RECUPERATION'
    AND status = 'APPROVED'
    AND EXTRACT(YEAR FROM start_date) = v_current_year;

  SELECT COALESCE(SUM(days_count), 0) INTO v_recup_pending
  FROM leave_requests
  WHERE user_id = p_user_id
    AND request_type = 'RECUPERATION'
    AND status IN ('PENDING', 'VALIDATED_RP', 'VALIDATED_DC')
    AND EXTRACT(YEAR FROM start_date) = v_current_year;

  -- Monthly accrual: calculate from RH-set balance_conge / 12 * current_month
  v_monthly_accrued := ROUND((v_user.balance_conge / 12.0 * v_current_month)::NUMERIC, 2)::FLOAT;

  -- Check 52-day cap
  v_is_max_reached := v_user.balance_conge >= v_max_balance;

  -- Recovery expiration date (June 30 of next year)
  v_recup_expires_at := make_date(v_current_year + 1, 6, 30);

  RETURN jsonb_build_object(
    'user_id',              p_user_id,
    'balance_conge',        v_user.balance_conge,
    'balance_recuperation', v_user.balance_recuperation,
    'annual_entitlement',   v_annual_entitlement,
    'days_used_this_year',  v_days_used_this_year,
    'days_pending',         v_days_pending,
    'recup_used',           v_recup_used,
    'recup_pending',        v_recup_pending,
    'entitlement_details',  v_entitlement,
    'monthly_accrued',      v_monthly_accrued,
    'monthly_rate',         ROUND((v_user.balance_conge / 12.0)::NUMERIC, 2)::FLOAT,
    'available_now',        GREATEST(v_monthly_accrued - v_days_used_this_year - v_days_pending, 0),
    'is_max_reached',       v_is_max_reached,
    'max_balance',          v_max_balance,
    'recup_expires_at',     v_recup_expires_at
  );
END;
$$;


-- ── REQ #8: Recovery request workflow RPCs ──

CREATE OR REPLACE FUNCTION submit_recovery_request(
  p_user_id    UUID,
  p_days       FLOAT,
  p_date_worked DATE,
  p_work_type  TEXT,
  p_reason     TEXT,
  p_period     TEXT DEFAULT 'FULL'
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_user    utilisateurs%ROWTYPE;
  v_request recovery_requests%ROWTYPE;
  v_days    FLOAT;
BEGIN
  SELECT * INTO v_user FROM utilisateurs WHERE id = p_user_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Utilisateur introuvable';
  END IF;

  -- Validate period
  IF p_period NOT IN ('MORNING', 'AFTERNOON', 'FULL') THEN
    RAISE EXCEPTION 'La periode doit etre MORNING, AFTERNOON ou FULL';
  END IF;

  -- Auto-calculate days from period if p_days is 0 or NULL
  IF p_days IS NULL OR p_days = 0 THEN
    IF p_period = 'FULL' THEN
      v_days := 1.0;
    ELSE
      v_days := 0.5;
    END IF;
  ELSE
    v_days := p_days;
  END IF;

  IF v_days <= 0 OR v_days > 5 THEN
    RAISE EXCEPTION 'Le nombre de jours doit etre entre 0.5 et 5';
  END IF;

  INSERT INTO recovery_requests (user_id, days, date_worked, work_type, period, reason)
  VALUES (p_user_id, v_days, p_date_worked, p_work_type::recovery_work_type, p_period, p_reason)
  RETURNING * INTO v_request;

  RETURN to_jsonb(v_request);
END;
$$;

CREATE OR REPLACE FUNCTION validate_recovery_request(
  p_request_id   BIGINT,
  p_validator_id UUID
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_request    recovery_requests%ROWTYPE;
  v_validator  utilisateurs%ROWTYPE;
  v_new_balance FLOAT;
  v_max_balance FLOAT := 52.0;
  v_expires_at  DATE;
BEGIN
  SELECT * INTO v_request FROM recovery_requests WHERE id = p_request_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Demande de recuperation introuvable';
  END IF;

  IF v_request.status != 'PENDING' THEN
    RAISE EXCEPTION 'Cette demande a deja ete traitee';
  END IF;

  SELECT * INTO v_validator FROM utilisateurs WHERE id = p_validator_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Validateur introuvable';
  END IF;

  -- Must be a manager
  IF v_validator.role::TEXT NOT IN ('CHEF_SERVICE', 'RH', 'DIRECTEUR_EXECUTIF', 'ADMIN') THEN
    RAISE EXCEPTION 'Seul un responsable peut valider les recuperations';
  END IF;

  -- Update status
  UPDATE recovery_requests
  SET status = 'VALIDATED', validated_by = p_validator_id, validated_at = NOW(), updated_at = NOW()
  WHERE id = p_request_id;

  -- Credit the balance
  UPDATE utilisateurs
  SET balance_recuperation = balance_recuperation + v_request.days
  WHERE id = v_request.user_id
  RETURNING balance_recuperation INTO v_new_balance;

  -- Create recovery lot with expiration (June 30 of N+1)
  v_expires_at := make_date(EXTRACT(YEAR FROM v_request.date_worked)::INT + 1, 6, 30);

  INSERT INTO recovery_balance_lots (user_id, days, remaining_days, year_acquired, expires_at, source_request_id)
  VALUES (v_request.user_id, v_request.days, v_request.days,
          EXTRACT(YEAR FROM v_request.date_worked)::INT, v_expires_at, p_request_id);

  -- Record in balance history
  INSERT INTO leave_balance_history (user_id, type, amount, reason, year, date_from, date_to, expires_at)
  VALUES (
    v_request.user_id, 'RECUPERATION', v_request.days,
    'Recuperation validee - ' || COALESCE(v_request.reason, v_request.work_type::TEXT),
    EXTRACT(YEAR FROM v_request.date_worked)::INT,
    v_request.date_worked, v_request.date_worked,
    v_expires_at
  );

  RETURN jsonb_build_object(
    'request_id',  p_request_id,
    'status',      'VALIDATED',
    'days',        v_request.days,
    'new_balance', v_new_balance,
    'expires_at',  v_expires_at
  );
END;
$$;

CREATE OR REPLACE FUNCTION reject_recovery_request(
  p_request_id   BIGINT,
  p_rejector_id  UUID,
  p_reason       TEXT
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_request   recovery_requests%ROWTYPE;
BEGIN
  SELECT * INTO v_request FROM recovery_requests WHERE id = p_request_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Demande de recuperation introuvable';
  END IF;

  IF v_request.status != 'PENDING' THEN
    RAISE EXCEPTION 'Cette demande a deja ete traitee';
  END IF;

  UPDATE recovery_requests
  SET status = 'REJECTED',
      validated_by = p_rejector_id,
      validated_at = NOW(),
      rejection_reason = p_reason,
      updated_at = NOW()
  WHERE id = p_request_id;

  RETURN jsonb_build_object(
    'request_id', p_request_id,
    'status',     'REJECTED',
    'reason',     p_reason
  );
END;
$$;


-- ── REQ #10: Expire recovery days (run on June 30) ──
CREATE OR REPLACE FUNCTION expire_recovery_days()
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_lot     RECORD;
  v_count   INT := 0;
  v_total   FLOAT := 0;
BEGIN
  FOR v_lot IN
    SELECT * FROM recovery_balance_lots
    WHERE expired = false AND expires_at <= CURRENT_DATE AND remaining_days > 0
  LOOP
    -- Deduct from user's recovery balance
    UPDATE utilisateurs
    SET balance_recuperation = GREATEST(balance_recuperation - v_lot.remaining_days, 0)
    WHERE id = v_lot.user_id;

    -- Record in history
    INSERT INTO leave_balance_history (user_id, type, amount, reason, year)
    VALUES (
      v_lot.user_id, 'RECUPERATION', -v_lot.remaining_days,
      'Expiration recuperation (acquise en ' || v_lot.year_acquired || ')',
      EXTRACT(YEAR FROM CURRENT_DATE)::INT
    );

    -- Mark lot as expired
    UPDATE recovery_balance_lots SET expired = true WHERE id = v_lot.id;

    v_total := v_total + v_lot.remaining_days;
    v_count := v_count + 1;
  END LOOP;

  RETURN jsonb_build_object(
    'lots_expired', v_count,
    'days_expired', v_total,
    'date',         CURRENT_DATE
  );
END;
$$;


-- ── REQ #12: Get role for specific company ──
CREATE OR REPLACE FUNCTION get_role_for_company(p_company_id BIGINT)
RETURNS TEXT
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_role TEXT;
BEGIN
  -- First check user_company_roles table
  SELECT role::TEXT INTO v_role
  FROM user_company_roles
  WHERE user_id = auth.uid() AND company_id = p_company_id AND is_active = true;

  IF FOUND THEN
    RETURN v_role;
  END IF;

  -- Fall back to default role from utilisateurs
  SELECT role::TEXT INTO v_role
  FROM utilisateurs
  WHERE id = auth.uid();

  RETURN v_role;
END;
$$;


-- ==============================================================================
-- GRANTS FOR NEW FUNCTIONS
-- ==============================================================================

GRANT EXECUTE ON FUNCTION count_working_days(DATE, DATE, BIGINT, BIGINT, TEXT, TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION accrue_monthly_balance(INT, INT) TO authenticated;
GRANT EXECUTE ON FUNCTION submit_recovery_request(UUID, FLOAT, DATE, TEXT, TEXT, TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION validate_recovery_request(BIGINT, UUID) TO authenticated;
GRANT EXECUTE ON FUNCTION reject_recovery_request(BIGINT, UUID, TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION expire_recovery_days() TO authenticated;
GRANT EXECUTE ON FUNCTION get_role_for_company(BIGINT) TO authenticated;


-- ==============================================================================
-- SEED: Ensure ATH and FRMG companies exist (Req #12)
-- ==============================================================================

INSERT INTO public.companies (name) VALUES ('ATH')
ON CONFLICT (name) DO NOTHING;

INSERT INTO public.companies (name) VALUES ('FRMG')
ON CONFLICT (name) DO NOTHING;


-- ==============================================================================
-- SEED: Default personnel categories for ATH and FRMG
-- ==============================================================================

INSERT INTO public.personnel_categories (company_id, name, description, annual_leave_days)
SELECT c.id, v.name, v.description, v.annual_leave_days
FROM (VALUES
  ('Cadre Supérieur',    'Directeurs et responsables de département',  24::float),
  ('Cadre',              'Ingénieurs, chefs de projet, managers',      21),
  ('Agent de Maîtrise',  'Techniciens supérieurs, superviseurs',       19.5),
  ('Employé',            'Personnel administratif et support',         18),
  ('Ouvrier',            'Personnel opérationnel et technique',        18),
  ('Chauffeur',          'Chauffeurs et conducteurs',                  18),
  ('Agent de Sécurité',  'Gardiens et agents de surveillance',         18),
  ('Agent d''Entretien', 'Personnel de nettoyage et maintenance',      18),
  ('Jardinier',          'Entretien des espaces verts et terrains',    18),
  ('Cuisinier',          'Personnel de restauration et cuisine',       18),
  ('Stagiaire',          'Stagiaires et contrats d''insertion',        15)
) AS v(name, description, annual_leave_days)
CROSS JOIN public.companies c
WHERE c.name IN ('ATH', 'FRMG')
ON CONFLICT (company_id, name) DO NOTHING;


-- ==============================================================================
-- SCHEMA UPDATE COMPLETE
-- ==============================================================================
