-- ==============================================================================
-- COMPLETE SCHEMA — SmartFlow Conge
-- ==============================================================================
-- Single consolidated migration for the entire database.
-- Run this on a fresh Supabase instance to set up everything.
--
-- Includes:
--   1. Enums & core tables (utilisateurs, leave_requests, mission_requests, etc.)
--   2. Indexes
--   3. Helper functions (get_my_role, is_manager, can_manage_user)
--   4. RLS policies for all tables
--   5. Triggers (leave & mission initial status, auto-approve, updated_at)
--   6. Leave RPCs (approve, reject, undo_approve, undo_reject)
--   7. Mission RPCs (approve, reject, undo_approve, undo_reject)
--   8. Moroccan labor law RPCs (count_working_days, entitlement, balance, credit_recuperation)
--   9. Balance init RPC (set_initial_balance)
--  10. Seed data (working days config, Moroccan public holidays)
--  11. Grants
--
-- Approval chains:
--   Leave:   PENDING -> RH -> VALIDATED_RP -> Chef -> VALIDATED_DC -> Dir -> APPROVED
--   Mission: PENDING -> Chef -> VALIDATED_DC -> RH -> VALIDATED_RP -> Dir -> APPROVED
--
-- Roles: EMPLOYEE, CHEF_SERVICE, RH (RESPONSABLE_PERSONNEL), DIRECTEUR_EXECUTIF, ADMIN
-- (TRESORIER_GENERAL kept in enum for backward compat but removed from active workflow)
-- ==============================================================================


-- ==============================================================================
-- SECTION 1: ENUMS
-- ==============================================================================

DO $$ BEGIN
    CREATE TYPE public.leave_request_type AS ENUM ('CONGE', 'RECUPERATION');
EXCEPTION WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE public.leave_status AS ENUM (
        'PENDING',
        'VALIDATED_DC',
        'VALIDATED_RP',
        'VALIDATED_TG',
        'VALIDATED_DE',
        'APPROVED',
        'REJECTED',
        'CANCELLED',
        'ARCHIVED'
    );
EXCEPTION WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE public.user_role AS ENUM (
        'EMPLOYEE',
        'CHEF_SERVICE',
        'RH',
        'TRESORIER_GENERAL',
        'DIRECTEUR_EXECUTIF',
        'ADMIN'
    );
EXCEPTION WHEN duplicate_object THEN null;
END $$;


-- ==============================================================================
-- SECTION 2: CORE TABLES
-- ==============================================================================

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- Companies
CREATE TABLE IF NOT EXISTS public.companies (
    id bigint generated by default as identity primary key,
    legacy_id text UNIQUE,
    name text NOT NULL UNIQUE,
    created_at timestamptz default now() not null,
    updated_at timestamptz default now() not null
);

-- Departments
CREATE TABLE IF NOT EXISTS public.departments (
    id bigint generated by default as identity primary key,
    legacy_id bigint UNIQUE,
    name text NOT NULL,
    company_id bigint references public.companies(id) ON DELETE CASCADE,
    filter_budget text,
    filter_article text,
    created_at timestamptz default now() not null,
    updated_at timestamptz default now() not null
);

-- Utilisateurs (standalone, no auth.users dependency for table creation)
CREATE TABLE IF NOT EXISTS public.utilisateurs (
    id uuid default gen_random_uuid() primary key,
    legacy_id bigint UNIQUE,
    email text UNIQUE,
    password_hash text,
    full_name text NOT NULL,
    username text UNIQUE,
    company_id bigint references public.companies(id),
    department_id bigint references public.departments(id),
    job_title text,
    role public.user_role default 'EMPLOYEE',
    is_active boolean default true,
    balance_conge float default 0,
    balance_recuperation float default 0,
    phone text,
    avatar_url text,
    hire_date date,
    birth_date date,
    matricule text,
    cin text,
    cnss text,
    rib text,
    address text,
    city text,
    gender text,
    legacy_profile_id int,
    is_signatory boolean default false,
    signatory_type text,
    signature_file text,
    last_login timestamptz,
    created_at timestamptz default now() not null,
    updated_at timestamptz default now() not null
);

-- Leave requests
CREATE TABLE IF NOT EXISTS public.leave_requests (
    id bigint generated by default as identity primary key,
    legacy_id bigint UNIQUE,
    user_id uuid references public.utilisateurs(id) NOT NULL,
    created_by uuid,
    request_type public.leave_request_type NOT NULL,
    start_date date NOT NULL,
    end_date date NOT NULL,
    days_count float NOT NULL,
    return_date date,
    replacement_user_id uuid references public.utilisateurs(id),
    status public.leave_status default 'PENDING',
    initial_status public.leave_status,
    reason text,
    comments text,
    balance_before float,
    balance_conge_used float,
    balance_recuperation_used float,
    approved_by_dc uuid references public.utilisateurs(id),
    approved_by_rp uuid references public.utilisateurs(id),
    approved_by_tg uuid references public.utilisateurs(id),
    approved_by_de uuid references public.utilisateurs(id),
    approved_at_dc timestamptz,
    approved_at_rp timestamptz,
    approved_at_tg timestamptz,
    approved_at_de timestamptz,
    rejected_by uuid references public.utilisateurs(id),
    rejected_at timestamptz,
    rejection_reason text,
    created_at timestamptz default now() not null,
    updated_at timestamptz default now() not null
);

-- Mission requests (Ordre de Mission)
CREATE TABLE IF NOT EXISTS public.mission_requests (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid REFERENCES public.utilisateurs(id) NOT NULL,
    assigned_by uuid REFERENCES public.utilisateurs(id),
    created_by uuid,
    request_origin TEXT NOT NULL DEFAULT 'SELF',
    mission_scope TEXT NOT NULL DEFAULT 'LOCAL',
    departure_city TEXT NOT NULL,
    arrival_city TEXT NOT NULL,
    mission_object TEXT NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    days_count FLOAT NOT NULL,
    transport_type TEXT,
    transport_details TEXT,
    replacement_user_id uuid REFERENCES public.utilisateurs(id),
    comments TEXT,
    status public.leave_status DEFAULT 'PENDING',
    initial_status public.leave_status,
    supervisor_opinion TEXT,
    supervisor_comments TEXT,
    supervisor_id uuid REFERENCES public.utilisateurs(id),
    supervisor_at TIMESTAMPTZ,
    approved_by_dc uuid REFERENCES public.utilisateurs(id),
    approved_by_rp uuid REFERENCES public.utilisateurs(id),
    approved_by_tg uuid REFERENCES public.utilisateurs(id),
    approved_by_de uuid REFERENCES public.utilisateurs(id),
    approved_at_dc TIMESTAMPTZ,
    approved_at_rp TIMESTAMPTZ,
    approved_at_tg TIMESTAMPTZ,
    approved_at_de TIMESTAMPTZ,
    director_decision TEXT,
    rejected_by uuid REFERENCES public.utilisateurs(id),
    rejected_at TIMESTAMPTZ,
    rejection_reason TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Leave balance history
CREATE TABLE IF NOT EXISTS public.leave_balance_history (
    id bigint generated by default as identity primary key,
    user_id uuid references public.utilisateurs(id) NOT NULL,
    type public.leave_request_type NOT NULL,
    amount float NOT NULL,
    reason text,
    year int,
    date_from date,
    date_to date,
    created_at timestamptz default now() not null
);

-- Working days configuration
CREATE TABLE IF NOT EXISTS public.working_days (
    id bigint generated by default as identity primary key,
    company_id bigint references public.companies(id),
    monday boolean default true,
    tuesday boolean default true,
    wednesday boolean default true,
    thursday boolean default true,
    friday boolean default true,
    saturday boolean default false,
    sunday boolean default false
);

-- Holidays
CREATE TABLE IF NOT EXISTS public.holidays (
    id bigint generated by default as identity primary key,
    company_id bigint references public.companies(id),
    name text NOT NULL,
    date date NOT NULL,
    is_recurring boolean default false,
    created_at timestamptz default now() not null
);

-- Notifications
CREATE TABLE IF NOT EXISTS public.notifications (
    id bigint generated by default as identity primary key,
    user_id uuid references public.utilisateurs(id) NOT NULL,
    title text NOT NULL,
    message text NOT NULL,
    type text,
    related_request_id bigint references public.leave_requests(id),
    is_read boolean default false,
    created_at timestamptz default now() not null
);

-- Audit logs
CREATE TABLE IF NOT EXISTS public.audit_logs (
    id bigint generated by default as identity primary key,
    table_name text NOT NULL,
    record_id bigint,
    action text NOT NULL,
    old_data jsonb,
    new_data jsonb,
    user_id uuid references public.utilisateurs(id),
    created_at timestamptz default now() not null
);


-- ==============================================================================
-- SECTION 3: INDEXES
-- ==============================================================================

CREATE INDEX IF NOT EXISTS idx_utilisateurs_company ON public.utilisateurs(company_id);
CREATE INDEX IF NOT EXISTS idx_utilisateurs_department ON public.utilisateurs(department_id);
CREATE INDEX IF NOT EXISTS idx_utilisateurs_role ON public.utilisateurs(role);
CREATE INDEX IF NOT EXISTS idx_utilisateurs_legacy_id ON public.utilisateurs(legacy_id);
CREATE INDEX IF NOT EXISTS idx_utilisateurs_email ON public.utilisateurs(email);
CREATE INDEX IF NOT EXISTS idx_leave_requests_user ON public.leave_requests(user_id);
CREATE INDEX IF NOT EXISTS idx_leave_requests_status ON public.leave_requests(status);
CREATE INDEX IF NOT EXISTS idx_leave_requests_dates ON public.leave_requests(start_date, end_date);
CREATE INDEX IF NOT EXISTS idx_notifications_user ON public.notifications(user_id, is_read);
CREATE INDEX IF NOT EXISTS idx_departments_legacy_id ON public.departments(legacy_id);
CREATE INDEX IF NOT EXISTS idx_mission_requests_user ON public.mission_requests(user_id);
CREATE INDEX IF NOT EXISTS idx_mission_requests_assigned_by ON public.mission_requests(assigned_by);
CREATE INDEX IF NOT EXISTS idx_mission_requests_status ON public.mission_requests(status);
CREATE INDEX IF NOT EXISTS idx_mission_requests_dates ON public.mission_requests(start_date, end_date);


-- ==============================================================================
-- SECTION 4: HELPER FUNCTIONS
-- ==============================================================================

-- Drop old versions first
DROP FUNCTION IF EXISTS public.get_my_role() CASCADE;
DROP FUNCTION IF EXISTS public.is_manager() CASCADE;
DROP FUNCTION IF EXISTS public.can_manage_user(UUID) CASCADE;

-- Get current user's role
CREATE OR REPLACE FUNCTION public.get_my_role()
RETURNS TEXT
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT role::TEXT FROM public.utilisateurs WHERE id = auth.uid();
$$;

-- Check if current user is a manager
CREATE OR REPLACE FUNCTION public.is_manager()
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT role::TEXT IN ('CHEF_SERVICE', 'RH', 'DIRECTEUR_EXECUTIF', 'ADMIN')
  FROM public.utilisateurs
  WHERE id = auth.uid();
$$;

-- Department-scoped management check
-- CHEF_SERVICE -> same department only
-- RH / DIRECTEUR_EXECUTIF / ADMIN -> full cross-department access
CREATE OR REPLACE FUNCTION public.can_manage_user(target_user_id UUID)
RETURNS boolean
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_role       TEXT;
  v_dept_id    BIGINT;
  v_target_dept BIGINT;
BEGIN
  SELECT role::TEXT, department_id
  INTO v_role, v_dept_id
  FROM public.utilisateurs
  WHERE id = auth.uid();

  IF NOT FOUND THEN
    RETURN FALSE;
  END IF;

  -- Global roles: full access
  IF v_role IN ('RH', 'DIRECTEUR_EXECUTIF', 'ADMIN') THEN
    RETURN TRUE;
  END IF;

  -- CHEF_SERVICE: same department only
  IF v_role = 'CHEF_SERVICE' AND v_dept_id IS NOT NULL THEN
    SELECT department_id INTO v_target_dept
    FROM public.utilisateurs
    WHERE id = target_user_id;

    RETURN v_dept_id = v_target_dept;
  END IF;

  RETURN FALSE;
END;
$$;


-- ==============================================================================
-- SECTION 5: RLS POLICIES
-- ==============================================================================

-- Clean slate
DO $$
DECLARE
  r RECORD;
BEGIN
  FOR r IN (
    SELECT policyname, tablename
    FROM pg_policies
    WHERE schemaname = 'public'
  )
  LOOP
    EXECUTE format('DROP POLICY IF EXISTS %I ON public.%I', r.policyname, r.tablename);
  END LOOP;
END $$;

ALTER TABLE IF EXISTS public.utilisateurs DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.leave_requests DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.companies DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.departments DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.leave_balance_history DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.notifications DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.holidays DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.working_days DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.audit_logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.mission_requests DISABLE ROW LEVEL SECURITY;


-- ── UTILISATEURS ──
ALTER TABLE public.utilisateurs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "utilisateurs_select_authenticated"
  ON public.utilisateurs FOR SELECT
  TO authenticated
  USING (true);

CREATE POLICY "utilisateurs_update_own_profile"
  ON public.utilisateurs FOR UPDATE
  TO authenticated
  USING (id = auth.uid())
  WITH CHECK (id = auth.uid());

CREATE POLICY "utilisateurs_update_manager"
  ON public.utilisateurs FOR UPDATE
  TO authenticated
  USING (public.is_manager());

CREATE POLICY "utilisateurs_insert_admin"
  ON public.utilisateurs FOR INSERT
  TO authenticated
  WITH CHECK (public.get_my_role() = 'ADMIN');

CREATE POLICY "utilisateurs_delete_admin"
  ON public.utilisateurs FOR DELETE
  TO authenticated
  USING (public.get_my_role() = 'ADMIN');


-- ── LEAVE_REQUESTS ──
ALTER TABLE public.leave_requests ENABLE ROW LEVEL SECURITY;

CREATE POLICY "leave_requests_select"
  ON public.leave_requests FOR SELECT
  TO authenticated
  USING (
    user_id = auth.uid()
    OR public.can_manage_user(user_id)
  );

CREATE POLICY "leave_requests_insert"
  ON public.leave_requests FOR INSERT
  TO authenticated
  WITH CHECK (
    user_id = auth.uid()
    OR public.can_manage_user(user_id)
  );

CREATE POLICY "leave_requests_update"
  ON public.leave_requests FOR UPDATE
  TO authenticated
  USING (
    (user_id = auth.uid() AND status = 'PENDING'::public.leave_status)
    OR (created_by = auth.uid() AND status = initial_status)
  )
  WITH CHECK (
    (user_id = auth.uid() AND status = 'PENDING'::public.leave_status)
    OR (created_by = auth.uid() AND status = initial_status)
  );

CREATE POLICY "leave_requests_delete"
  ON public.leave_requests FOR DELETE
  TO authenticated
  USING (
    (user_id = auth.uid() AND status = 'PENDING'::public.leave_status)
    OR (created_by = auth.uid() AND status = initial_status AND status != 'APPROVED'::public.leave_status)
    OR public.get_my_role() = 'ADMIN'
  );


-- ── MISSION_REQUESTS ──
ALTER TABLE public.mission_requests ENABLE ROW LEVEL SECURITY;

CREATE POLICY "mission_requests_select_own"
  ON public.mission_requests FOR SELECT
  TO authenticated
  USING (auth.uid() = user_id OR auth.uid() = assigned_by);

CREATE POLICY "mission_requests_select_manager"
  ON public.mission_requests FOR SELECT
  TO authenticated
  USING (public.can_manage_user(user_id));

CREATE POLICY "mission_requests_insert_self"
  ON public.mission_requests FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "mission_requests_insert_manager"
  ON public.mission_requests FOR INSERT
  TO authenticated
  WITH CHECK (public.can_manage_user(user_id));

CREATE POLICY "mission_requests_update"
  ON public.mission_requests FOR UPDATE
  TO authenticated
  USING (
    (user_id = auth.uid() AND status = 'PENDING'::public.leave_status)
    OR (created_by = auth.uid() AND status = initial_status)
  )
  WITH CHECK (
    (user_id = auth.uid() AND status = 'PENDING'::public.leave_status)
    OR (created_by = auth.uid() AND status = initial_status)
  );

CREATE POLICY "mission_requests_delete"
  ON public.mission_requests FOR DELETE
  TO authenticated
  USING (
    (user_id = auth.uid() AND status = 'PENDING'::public.leave_status)
    OR (created_by = auth.uid() AND status = initial_status AND status != 'APPROVED'::public.leave_status)
    OR public.get_my_role() = 'ADMIN'
  );


-- ── COMPANIES ──
ALTER TABLE public.companies ENABLE ROW LEVEL SECURITY;

CREATE POLICY "companies_select_authenticated"
  ON public.companies FOR SELECT TO authenticated USING (true);

CREATE POLICY "companies_manage_admin"
  ON public.companies FOR ALL TO authenticated
  USING (public.get_my_role() = 'ADMIN')
  WITH CHECK (public.get_my_role() = 'ADMIN');


-- ── DEPARTMENTS ──
ALTER TABLE public.departments ENABLE ROW LEVEL SECURITY;

CREATE POLICY "departments_select_authenticated"
  ON public.departments FOR SELECT TO authenticated USING (true);

CREATE POLICY "departments_manage_admin"
  ON public.departments FOR ALL TO authenticated
  USING (public.get_my_role() = 'ADMIN')
  WITH CHECK (public.get_my_role() = 'ADMIN');


-- ── LEAVE_BALANCE_HISTORY ──
ALTER TABLE public.leave_balance_history ENABLE ROW LEVEL SECURITY;

CREATE POLICY "balance_history_select"
  ON public.leave_balance_history FOR SELECT
  TO authenticated
  USING (
    user_id = auth.uid()
    OR public.can_manage_user(user_id)
  );

CREATE POLICY "balance_history_insert_manager"
  ON public.leave_balance_history FOR INSERT
  TO authenticated
  WITH CHECK (public.can_manage_user(user_id));

CREATE POLICY "balance_history_manage_admin"
  ON public.leave_balance_history FOR ALL
  TO authenticated
  USING (public.get_my_role() = 'ADMIN')
  WITH CHECK (public.get_my_role() = 'ADMIN');


-- ── NOTIFICATIONS ──
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;

CREATE POLICY "notifications_select_own"
  ON public.notifications FOR SELECT TO authenticated
  USING (user_id = auth.uid());

CREATE POLICY "notifications_update_own"
  ON public.notifications FOR UPDATE TO authenticated
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

CREATE POLICY "notifications_insert"
  ON public.notifications FOR INSERT TO authenticated
  WITH CHECK (true);

CREATE POLICY "notifications_delete_own"
  ON public.notifications FOR DELETE TO authenticated
  USING (user_id = auth.uid());


-- ── HOLIDAYS ──
ALTER TABLE public.holidays ENABLE ROW LEVEL SECURITY;

CREATE POLICY "holidays_select_authenticated"
  ON public.holidays FOR SELECT TO authenticated USING (true);

CREATE POLICY "holidays_manage_admin"
  ON public.holidays FOR ALL TO authenticated
  USING (public.get_my_role() = 'ADMIN')
  WITH CHECK (public.get_my_role() = 'ADMIN');


-- ── WORKING_DAYS ──
ALTER TABLE public.working_days ENABLE ROW LEVEL SECURITY;

CREATE POLICY "working_days_select_authenticated"
  ON public.working_days FOR SELECT TO authenticated USING (true);

CREATE POLICY "working_days_manage_admin"
  ON public.working_days FOR ALL TO authenticated
  USING (public.get_my_role() = 'ADMIN')
  WITH CHECK (public.get_my_role() = 'ADMIN');


-- ── AUDIT_LOGS ──
ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "audit_logs_admin_only"
  ON public.audit_logs FOR ALL TO authenticated
  USING (public.get_my_role() = 'ADMIN')
  WITH CHECK (public.get_my_role() = 'ADMIN');


-- ==============================================================================
-- SECTION 6: TRIGGERS
-- ==============================================================================

-- ── Leave: Compute initial status based on creator's role ──

DROP TRIGGER IF EXISTS trg_compute_initial_leave_status ON public.leave_requests;
DROP FUNCTION IF EXISTS public.compute_initial_leave_status() CASCADE;

CREATE OR REPLACE FUNCTION public.compute_initial_leave_status()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_creator_role TEXT;
BEGIN
  IF auth.uid() IS NOT NULL THEN
    NEW.created_by := auth.uid();
  END IF;

  -- Service role / dashboard: keep status as provided
  IF auth.uid() IS NULL THEN
    NEW.initial_status := COALESCE(NEW.status, 'PENDING'::public.leave_status);
    NEW.status := COALESCE(NEW.status, 'PENDING'::public.leave_status);
    RETURN NEW;
  END IF;

  SELECT role::TEXT INTO v_creator_role
  FROM utilisateurs WHERE id = auth.uid();

  -- DIR/ADMIN: auto-approve
  IF v_creator_role IN ('DIRECTEUR_EXECUTIF', 'ADMIN') THEN
    NEW.status := 'APPROVED'::public.leave_status;
    NEW.approved_by_de := auth.uid();
    NEW.approved_at_de := NOW();
    NEW.initial_status := 'APPROVED'::public.leave_status;
    RETURN NEW;
  END IF;

  -- RH self: skip RH+CHEF -> DIR
  IF v_creator_role = 'RH' AND NEW.user_id = auth.uid() THEN
    NEW.status := 'VALIDATED_DC'::public.leave_status;
    NEW.approved_by_rp := auth.uid();
    NEW.approved_at_rp := NOW();
    NEW.initial_status := 'VALIDATED_DC'::public.leave_status;
    RETURN NEW;
  END IF;

  -- RH on behalf: skip RH -> CHEF
  IF v_creator_role = 'RH' AND NEW.user_id != auth.uid() THEN
    NEW.status := 'VALIDATED_RP'::public.leave_status;
    NEW.approved_by_rp := auth.uid();
    NEW.approved_at_rp := NOW();
    NEW.initial_status := 'VALIDATED_RP'::public.leave_status;
    RETURN NEW;
  END IF;

  -- CHEF self or on behalf: skip RH+CHEF -> DIR
  IF v_creator_role = 'CHEF_SERVICE' THEN
    NEW.status := 'VALIDATED_DC'::public.leave_status;
    NEW.approved_by_dc := auth.uid();
    NEW.approved_at_dc := NOW();
    NEW.initial_status := 'VALIDATED_DC'::public.leave_status;
    RETURN NEW;
  END IF;

  -- EMPLOYEE: PENDING -> full chain
  NEW.status := 'PENDING'::public.leave_status;
  NEW.initial_status := 'PENDING'::public.leave_status;
  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_compute_initial_leave_status
  BEFORE INSERT ON public.leave_requests
  FOR EACH ROW
  EXECUTE FUNCTION public.compute_initial_leave_status();


-- ── Leave: Handle balance deduction for auto-approved requests ──

DROP TRIGGER IF EXISTS trg_handle_auto_approved_leave ON public.leave_requests;
DROP FUNCTION IF EXISTS public.handle_auto_approved_leave() CASCADE;

CREATE OR REPLACE FUNCTION public.handle_auto_approved_leave()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NEW.status = 'APPROVED'::public.leave_status THEN
    IF NEW.request_type = 'CONGE' THEN
      UPDATE utilisateurs
      SET balance_conge = balance_conge - NEW.days_count
      WHERE id = NEW.user_id;
    ELSE
      UPDATE utilisateurs
      SET balance_recuperation = balance_recuperation - NEW.days_count
      WHERE id = NEW.user_id;
    END IF;

    INSERT INTO leave_balance_history (user_id, type, amount, reason, year, date_from, date_to)
    VALUES (
      NEW.user_id,
      NEW.request_type,
      -NEW.days_count,
      'Demande auto-approuvee #' || NEW.id,
      EXTRACT(YEAR FROM NEW.start_date)::INT,
      NEW.start_date,
      NEW.end_date
    );
  END IF;

  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_handle_auto_approved_leave
  AFTER INSERT ON public.leave_requests
  FOR EACH ROW
  EXECUTE FUNCTION public.handle_auto_approved_leave();


-- ── Mission: Compute initial status based on creator's role ──

DROP TRIGGER IF EXISTS trg_compute_initial_mission_status ON public.mission_requests;
DROP FUNCTION IF EXISTS public.compute_initial_mission_status() CASCADE;

CREATE OR REPLACE FUNCTION public.compute_initial_mission_status()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_creator_role TEXT;
BEGIN
  IF auth.uid() IS NOT NULL THEN
    NEW.created_by := auth.uid();
  END IF;

  IF auth.uid() IS NULL THEN
    NEW.initial_status := COALESCE(NEW.status, 'PENDING'::public.leave_status);
    NEW.status := COALESCE(NEW.status, 'PENDING'::public.leave_status);
    RETURN NEW;
  END IF;

  SELECT role::TEXT INTO v_creator_role
  FROM utilisateurs WHERE id = auth.uid();

  -- DIR/ADMIN: auto-approve
  IF v_creator_role IN ('DIRECTEUR_EXECUTIF', 'ADMIN') THEN
    NEW.status := 'APPROVED'::public.leave_status;
    NEW.approved_by_de := auth.uid();
    NEW.approved_at_de := NOW();
    NEW.director_decision := 'ACCORDEE';
    NEW.initial_status := 'APPROVED'::public.leave_status;
    RETURN NEW;
  END IF;

  -- RH self: skip Chef+RH -> DIR
  IF v_creator_role = 'RH' AND NEW.user_id = auth.uid() THEN
    NEW.status := 'VALIDATED_RP'::public.leave_status;
    NEW.approved_by_dc := auth.uid();
    NEW.approved_at_dc := NOW();
    NEW.approved_by_rp := auth.uid();
    NEW.approved_at_rp := NOW();
    NEW.initial_status := 'VALIDATED_RP'::public.leave_status;
    RETURN NEW;
  END IF;

  -- RH on behalf: Chef must approve first (RH step auto-skipped in approve RPC)
  IF v_creator_role = 'RH' AND NEW.user_id != auth.uid() THEN
    NEW.status := 'PENDING'::public.leave_status;
    NEW.initial_status := 'PENDING'::public.leave_status;
    RETURN NEW;
  END IF;

  -- CHEF (self or on behalf): skip Chef step -> RH
  IF v_creator_role = 'CHEF_SERVICE' THEN
    NEW.status := 'VALIDATED_DC'::public.leave_status;
    NEW.approved_by_dc := auth.uid();
    NEW.approved_at_dc := NOW();
    NEW.initial_status := 'VALIDATED_DC'::public.leave_status;
    RETURN NEW;
  END IF;

  -- EMPLOYEE: PENDING -> full chain
  NEW.status := 'PENDING'::public.leave_status;
  NEW.initial_status := 'PENDING'::public.leave_status;
  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_compute_initial_mission_status
  BEFORE INSERT ON public.mission_requests
  FOR EACH ROW
  EXECUTE FUNCTION public.compute_initial_mission_status();


-- ── Mission: Auto-update updated_at ──

DROP TRIGGER IF EXISTS trigger_mission_updated_at ON public.mission_requests;
DROP FUNCTION IF EXISTS update_mission_updated_at() CASCADE;

CREATE OR REPLACE FUNCTION update_mission_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_mission_updated_at
    BEFORE UPDATE ON public.mission_requests
    FOR EACH ROW
    EXECUTE FUNCTION update_mission_updated_at();


-- ==============================================================================
-- SECTION 7: LEAVE REQUEST RPCs
-- ==============================================================================

DROP FUNCTION IF EXISTS public.approve_leave_request(BIGINT, UUID, DATE, DATE, FLOAT) CASCADE;
DROP FUNCTION IF EXISTS public.reject_leave_request(BIGINT, UUID, TEXT) CASCADE;
DROP FUNCTION IF EXISTS public.undo_approve_leave_request(BIGINT, UUID) CASCADE;
DROP FUNCTION IF EXISTS public.undo_reject_leave_request(BIGINT, UUID) CASCADE;

-- ── APPROVE LEAVE REQUEST ──
-- 3-stage: PENDING->RH->VALIDATED_RP, VALIDATED_RP->CHEF->VALIDATED_DC, VALIDATED_DC->DIR->APPROVED
-- On final approval: recalculates days (holiday-aware), deducts balance, records history
CREATE OR REPLACE FUNCTION public.approve_leave_request(
  p_request_id     BIGINT,
  p_approver_id    UUID,
  p_new_start_date DATE DEFAULT NULL,
  p_new_end_date   DATE DEFAULT NULL,
  p_new_days_count FLOAT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_request            leave_requests%ROWTYPE;
  v_approver           utilisateurs%ROWTYPE;
  v_request_user       utilisateurs%ROWTYPE;
  v_expected_role      TEXT;
  v_next_status        TEXT;
  v_field              TEXT;
  v_days               FLOAT;
  v_balance_field      TEXT;
  v_requester_dept_id  BIGINT;
  v_company_id         BIGINT;
BEGIN
  SELECT * INTO v_request FROM leave_requests WHERE id = p_request_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Demande #% introuvable', p_request_id;
  END IF;

  SELECT * INTO v_approver FROM utilisateurs WHERE id = p_approver_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Approbateur introuvable';
  END IF;

  -- Prevent self-approval
  IF p_approver_id = v_request.user_id THEN
    RAISE EXCEPTION 'Vous ne pouvez pas approuver votre propre demande';
  END IF;

  CASE v_request.status
    WHEN 'PENDING'::public.leave_status THEN
      v_expected_role := 'RH';
      v_next_status := 'VALIDATED_RP';
      v_field := 'rp';
    WHEN 'VALIDATED_RP'::public.leave_status THEN
      v_expected_role := 'CHEF_SERVICE';
      v_next_status := 'VALIDATED_DC';
      v_field := 'dc';
    WHEN 'VALIDATED_DC'::public.leave_status THEN
      v_expected_role := 'DIRECTEUR_EXECUTIF';
      v_next_status := 'APPROVED';
      v_field := 'de';
    ELSE
      RAISE EXCEPTION 'La demande #% est au statut %, elle ne peut pas etre approuvee',
        p_request_id, v_request.status;
  END CASE;

  -- Role check (ADMIN can act at any step)
  IF v_approver.role::TEXT != v_expected_role AND v_approver.role::TEXT != 'ADMIN' THEN
    RAISE EXCEPTION 'Seul le role % peut approuver a cette etape (vous etes %)',
      v_expected_role, v_approver.role;
  END IF;

  -- Department check for CHEF_SERVICE
  IF v_approver.role::TEXT = 'CHEF_SERVICE' THEN
    SELECT department_id INTO v_requester_dept_id
    FROM utilisateurs WHERE id = v_request.user_id;

    IF v_approver.department_id IS NULL
       OR v_requester_dept_id IS NULL
       OR v_approver.department_id != v_requester_dept_id THEN
      RAISE EXCEPTION 'Le chef de service ne peut approuver que les demandes de son departement';
    END IF;
  END IF;

  -- RH can edit dates at PENDING stage
  IF v_field = 'rp' AND p_new_start_date IS NOT NULL AND p_new_end_date IS NOT NULL THEN
    UPDATE leave_requests SET
      start_date = p_new_start_date,
      end_date = p_new_end_date,
      days_count = COALESCE(p_new_days_count, v_request.days_count)
    WHERE id = p_request_id;
    SELECT * INTO v_request FROM leave_requests WHERE id = p_request_id;
  END IF;

  v_days := v_request.days_count;

  -- Update status and approval fields
  EXECUTE format(
    'UPDATE leave_requests SET status = $1::public.leave_status, approved_by_%s = $2, approved_at_%s = NOW(), updated_at = NOW() WHERE id = $3',
    v_field, v_field
  ) USING v_next_status, p_approver_id, p_request_id;

  -- On final approval: recalculate days, deduct balance, record history
  IF v_next_status = 'APPROVED' THEN
    SELECT * INTO v_request_user FROM utilisateurs WHERE id = v_request.user_id;
    v_company_id := COALESCE(v_request_user.company_id, (SELECT id FROM companies LIMIT 1));

    -- Recalculate days server-side (holiday-aware)
    v_days := count_working_days(v_request.start_date, v_request.end_date, v_company_id);
    UPDATE leave_requests SET days_count = v_days WHERE id = p_request_id;

    IF v_request.request_type = 'CONGE' THEN
      v_balance_field := 'balance_conge';
    ELSE
      v_balance_field := 'balance_recuperation';
    END IF;

    EXECUTE format(
      'UPDATE utilisateurs SET %I = GREATEST(%I - $1, 0) WHERE id = $2',
      v_balance_field, v_balance_field
    ) USING v_days, v_request.user_id;

    INSERT INTO leave_balance_history (user_id, type, amount, reason, year, date_from, date_to)
    VALUES (
      v_request.user_id,
      v_request.request_type,
      -v_days,
      'Demande approuvee #' || p_request_id,
      EXTRACT(YEAR FROM v_request.start_date)::INT,
      v_request.start_date,
      v_request.end_date
    );
  END IF;

  RETURN (SELECT to_jsonb(lr.*) FROM leave_requests lr WHERE lr.id = p_request_id);
END;
$$;


-- ── REJECT LEAVE REQUEST ──
CREATE OR REPLACE FUNCTION public.reject_leave_request(
  p_request_id  BIGINT,
  p_rejector_id UUID,
  p_reason      TEXT
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_request            leave_requests%ROWTYPE;
  v_rejector           utilisateurs%ROWTYPE;
  v_requester_dept_id  BIGINT;
BEGIN
  SELECT * INTO v_request FROM leave_requests WHERE id = p_request_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Demande #% introuvable', p_request_id;
  END IF;

  SELECT * INTO v_rejector FROM utilisateurs WHERE id = p_rejector_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Utilisateur introuvable';
  END IF;

  IF p_reason IS NULL OR TRIM(p_reason) = '' THEN
    RAISE EXCEPTION 'La raison du rejet est obligatoire';
  END IF;

  -- Stage-role matching (ADMIN can reject at any stage)
  IF v_rejector.role::TEXT != 'ADMIN' THEN
    CASE v_request.status
      WHEN 'PENDING'::public.leave_status THEN
        IF v_rejector.role::TEXT != 'RH' THEN
          RAISE EXCEPTION 'Seul le RH peut rejeter a cette etape';
        END IF;
      WHEN 'VALIDATED_RP'::public.leave_status THEN
        IF v_rejector.role::TEXT != 'CHEF_SERVICE' THEN
          RAISE EXCEPTION 'Seul le Chef de Service peut rejeter a cette etape';
        END IF;
        SELECT department_id INTO v_requester_dept_id
        FROM utilisateurs WHERE id = v_request.user_id;
        IF v_rejector.department_id IS NULL
           OR v_requester_dept_id IS NULL
           OR v_rejector.department_id != v_requester_dept_id THEN
          RAISE EXCEPTION 'Le chef de service ne peut rejeter que les demandes de son departement';
        END IF;
      WHEN 'VALIDATED_DC'::public.leave_status THEN
        IF v_rejector.role::TEXT != 'DIRECTEUR_EXECUTIF' THEN
          RAISE EXCEPTION 'Seul le Directeur Executif peut rejeter a cette etape';
        END IF;
      ELSE
        RAISE EXCEPTION 'La demande #% est au statut %, elle ne peut pas etre rejetee',
          p_request_id, v_request.status;
    END CASE;
  ELSE
    IF v_request.status NOT IN ('PENDING'::public.leave_status, 'VALIDATED_RP'::public.leave_status, 'VALIDATED_DC'::public.leave_status) THEN
      RAISE EXCEPTION 'La demande #% est au statut %, elle ne peut pas etre rejetee',
        p_request_id, v_request.status;
    END IF;
  END IF;

  UPDATE leave_requests SET
    status = 'REJECTED'::public.leave_status,
    rejected_by = p_rejector_id,
    rejected_at = NOW(),
    rejection_reason = TRIM(p_reason),
    updated_at = NOW()
  WHERE id = p_request_id;

  RETURN (SELECT to_jsonb(lr.*) FROM leave_requests lr WHERE lr.id = p_request_id);
END;
$$;


-- ── UNDO APPROVE LEAVE ──
CREATE OR REPLACE FUNCTION public.undo_approve_leave_request(
  p_request_id BIGINT,
  p_user_id    UUID
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_request      leave_requests%ROWTYPE;
  v_user         utilisateurs%ROWTYPE;
  v_prev_status  TEXT;
  v_field        TEXT;
  v_balance_field TEXT;
BEGIN
  SELECT * INTO v_request FROM leave_requests WHERE id = p_request_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Demande #% introuvable', p_request_id;
  END IF;

  SELECT * INTO v_user FROM utilisateurs WHERE id = p_user_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Utilisateur introuvable';
  END IF;

  IF v_request.status = v_request.initial_status THEN
    RAISE EXCEPTION 'Impossible d''annuler: la demande est a son statut initial';
  END IF;

  CASE v_request.status
    WHEN 'VALIDATED_RP'::public.leave_status THEN
      v_prev_status := 'PENDING';
      v_field := 'rp';
      IF v_user.role::TEXT != 'ADMIN' AND v_request.approved_by_rp != p_user_id THEN
        RAISE EXCEPTION 'Seul l''approbateur ou un admin peut annuler cette validation';
      END IF;
    WHEN 'VALIDATED_DC'::public.leave_status THEN
      v_prev_status := 'VALIDATED_RP';
      v_field := 'dc';
      IF v_user.role::TEXT != 'ADMIN' AND v_request.approved_by_dc != p_user_id THEN
        RAISE EXCEPTION 'Seul l''approbateur ou un admin peut annuler cette validation';
      END IF;
      IF v_request.initial_status = 'VALIDATED_DC'::public.leave_status THEN
        RAISE EXCEPTION 'Impossible d''annuler: la demande est a son statut initial';
      END IF;
    WHEN 'APPROVED'::public.leave_status THEN
      v_prev_status := 'VALIDATED_DC';
      v_field := 'de';
      IF v_user.role::TEXT != 'ADMIN' AND v_request.approved_by_de != p_user_id THEN
        RAISE EXCEPTION 'Seul l''approbateur ou un admin peut annuler cette validation';
      END IF;

      -- Reverse balance deduction
      IF v_request.request_type = 'CONGE' THEN
        v_balance_field := 'balance_conge';
      ELSE
        v_balance_field := 'balance_recuperation';
      END IF;

      EXECUTE format(
        'UPDATE utilisateurs SET %I = %I + $1 WHERE id = $2',
        v_balance_field, v_balance_field
      ) USING v_request.days_count, v_request.user_id;

      INSERT INTO leave_balance_history (user_id, type, amount, reason, year, date_from, date_to)
      VALUES (
        v_request.user_id,
        v_request.request_type,
        v_request.days_count,
        'Annulation approbation demande #' || p_request_id,
        EXTRACT(YEAR FROM v_request.start_date)::INT,
        v_request.start_date,
        v_request.end_date
      );
    ELSE
      RAISE EXCEPTION 'La demande #% est au statut %, impossible d''annuler', p_request_id, v_request.status;
  END CASE;

  EXECUTE format(
    'UPDATE leave_requests SET status = $1::public.leave_status, approved_by_%s = NULL, approved_at_%s = NULL, updated_at = NOW() WHERE id = $2',
    v_field, v_field
  ) USING v_prev_status, p_request_id;

  RETURN (SELECT to_jsonb(lr.*) FROM leave_requests lr WHERE lr.id = p_request_id);
END;
$$;


-- ── UNDO REJECT LEAVE ──
CREATE OR REPLACE FUNCTION public.undo_reject_leave_request(
  p_request_id BIGINT,
  p_user_id    UUID
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_request        leave_requests%ROWTYPE;
  v_user           utilisateurs%ROWTYPE;
  v_restore_status TEXT;
BEGIN
  SELECT * INTO v_request FROM leave_requests WHERE id = p_request_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Demande #% introuvable', p_request_id;
  END IF;

  IF v_request.status != 'REJECTED'::public.leave_status THEN
    RAISE EXCEPTION 'La demande #% n''est pas rejetee', p_request_id;
  END IF;

  SELECT * INTO v_user FROM utilisateurs WHERE id = p_user_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Utilisateur introuvable';
  END IF;

  IF v_user.role::TEXT != 'ADMIN' AND v_request.rejected_by != p_user_id THEN
    RAISE EXCEPTION 'Seul la personne qui a rejete ou un admin peut restaurer cette demande';
  END IF;

  IF v_request.approved_by_dc IS NOT NULL THEN
    v_restore_status := 'VALIDATED_DC';
  ELSIF v_request.approved_by_rp IS NOT NULL THEN
    v_restore_status := 'VALIDATED_RP';
  ELSE
    v_restore_status := 'PENDING';
  END IF;

  IF v_restore_status = 'PENDING' AND v_request.initial_status != 'PENDING'::public.leave_status THEN
    v_restore_status := v_request.initial_status::TEXT;
  ELSIF v_restore_status = 'VALIDATED_RP'
        AND v_request.initial_status IN ('VALIDATED_DC'::public.leave_status, 'APPROVED'::public.leave_status) THEN
    v_restore_status := v_request.initial_status::TEXT;
  END IF;

  UPDATE leave_requests SET
    status = v_restore_status::public.leave_status,
    rejected_by = NULL,
    rejected_at = NULL,
    rejection_reason = NULL,
    updated_at = NOW()
  WHERE id = p_request_id;

  RETURN (SELECT to_jsonb(lr.*) FROM leave_requests lr WHERE lr.id = p_request_id);
END;
$$;


-- ==============================================================================
-- SECTION 8: MISSION REQUEST RPCs
-- ==============================================================================

DROP FUNCTION IF EXISTS public.approve_mission_request(BIGINT, UUID) CASCADE;
DROP FUNCTION IF EXISTS public.reject_mission_request(BIGINT, UUID, TEXT) CASCADE;
DROP FUNCTION IF EXISTS public.undo_approve_mission_request(BIGINT, UUID) CASCADE;
DROP FUNCTION IF EXISTS public.undo_reject_mission_request(BIGINT, UUID) CASCADE;

-- ── APPROVE MISSION REQUEST ──
-- Mission chain: PENDING->Chef(dc) -> VALIDATED_DC->RH(rp) -> VALIDATED_RP->Dir(de) -> APPROVED
-- Auto-skips RH step when creator is RH (on-behalf case)
CREATE OR REPLACE FUNCTION public.approve_mission_request(
  p_request_id  BIGINT,
  p_approver_id UUID
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_request            mission_requests%ROWTYPE;
  v_approver           utilisateurs%ROWTYPE;
  v_expected_role      TEXT;
  v_next_status        TEXT;
  v_field              TEXT;
  v_requester_dept_id  BIGINT;
  v_creator_role       TEXT;
BEGIN
  SELECT * INTO v_request FROM mission_requests WHERE id = p_request_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Demande de mission #% introuvable', p_request_id;
  END IF;

  SELECT * INTO v_approver FROM utilisateurs WHERE id = p_approver_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Approbateur introuvable';
  END IF;

  IF p_approver_id = v_request.user_id THEN
    RAISE EXCEPTION 'Vous ne pouvez pas approuver votre propre demande';
  END IF;

  CASE v_request.status
    WHEN 'PENDING'::public.leave_status THEN
      v_expected_role := 'CHEF_SERVICE';
      v_next_status := 'VALIDATED_DC';
      v_field := 'dc';
    WHEN 'VALIDATED_DC'::public.leave_status THEN
      v_expected_role := 'RH';
      v_next_status := 'VALIDATED_RP';
      v_field := 'rp';
    WHEN 'VALIDATED_RP'::public.leave_status THEN
      v_expected_role := 'DIRECTEUR_EXECUTIF';
      v_next_status := 'APPROVED';
      v_field := 'de';
    ELSE
      RAISE EXCEPTION 'La demande de mission #% est au statut %, elle ne peut pas etre approuvee',
        p_request_id, v_request.status;
  END CASE;

  IF v_approver.role::TEXT != v_expected_role AND v_approver.role::TEXT != 'ADMIN' THEN
    RAISE EXCEPTION 'Seul le role % peut approuver a cette etape (vous etes %)',
      v_expected_role, v_approver.role;
  END IF;

  -- Department check for CHEF_SERVICE
  IF v_approver.role::TEXT = 'CHEF_SERVICE' THEN
    SELECT department_id INTO v_requester_dept_id
    FROM utilisateurs WHERE id = v_request.user_id;

    IF v_approver.department_id IS NULL
       OR v_requester_dept_id IS NULL
       OR v_approver.department_id != v_requester_dept_id THEN
      RAISE EXCEPTION 'Le chef de service ne peut approuver que les demandes de son departement';
    END IF;
  END IF;

  EXECUTE format(
    'UPDATE mission_requests SET status = $1::public.leave_status, approved_by_%s = $2, approved_at_%s = NOW(), updated_at = NOW() WHERE id = $3',
    v_field, v_field
  ) USING v_next_status, p_approver_id, p_request_id;

  IF v_next_status = 'APPROVED' THEN
    UPDATE mission_requests SET director_decision = 'ACCORDEE' WHERE id = p_request_id;
  END IF;

  -- Auto-skip RH step if creator is RH (on-behalf case)
  IF v_next_status = 'VALIDATED_DC' AND v_request.created_by IS NOT NULL THEN
    SELECT role::TEXT INTO v_creator_role
    FROM utilisateurs WHERE id = v_request.created_by;

    IF v_creator_role = 'RH' THEN
      UPDATE mission_requests SET
        status = 'VALIDATED_RP'::public.leave_status,
        approved_by_rp = v_request.created_by,
        approved_at_rp = NOW(),
        updated_at = NOW()
      WHERE id = p_request_id;
    END IF;
  END IF;

  RETURN (SELECT to_jsonb(mr.*) FROM mission_requests mr WHERE mr.id = p_request_id);
END;
$$;


-- ── REJECT MISSION REQUEST ──
CREATE OR REPLACE FUNCTION public.reject_mission_request(
  p_request_id  BIGINT,
  p_rejector_id UUID,
  p_reason      TEXT
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_request            mission_requests%ROWTYPE;
  v_rejector           utilisateurs%ROWTYPE;
  v_requester_dept_id  BIGINT;
BEGIN
  SELECT * INTO v_request FROM mission_requests WHERE id = p_request_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Demande de mission #% introuvable', p_request_id;
  END IF;

  SELECT * INTO v_rejector FROM utilisateurs WHERE id = p_rejector_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Utilisateur introuvable';
  END IF;

  IF p_reason IS NULL OR TRIM(p_reason) = '' THEN
    RAISE EXCEPTION 'La raison du rejet est obligatoire';
  END IF;

  IF v_rejector.role::TEXT != 'ADMIN' THEN
    CASE v_request.status
      WHEN 'PENDING'::public.leave_status THEN
        IF v_rejector.role::TEXT != 'CHEF_SERVICE' THEN
          RAISE EXCEPTION 'Seul le Chef de Service peut rejeter a cette etape';
        END IF;
        SELECT department_id INTO v_requester_dept_id
        FROM utilisateurs WHERE id = v_request.user_id;
        IF v_rejector.department_id IS NULL
           OR v_requester_dept_id IS NULL
           OR v_rejector.department_id != v_requester_dept_id THEN
          RAISE EXCEPTION 'Le chef de service ne peut rejeter que les demandes de son departement';
        END IF;
      WHEN 'VALIDATED_DC'::public.leave_status THEN
        IF v_rejector.role::TEXT != 'RH' THEN
          RAISE EXCEPTION 'Seul le RH peut rejeter a cette etape';
        END IF;
      WHEN 'VALIDATED_RP'::public.leave_status THEN
        IF v_rejector.role::TEXT != 'DIRECTEUR_EXECUTIF' THEN
          RAISE EXCEPTION 'Seul le Directeur Executif peut rejeter a cette etape';
        END IF;
      ELSE
        RAISE EXCEPTION 'La demande de mission #% est au statut %, elle ne peut pas etre rejetee',
          p_request_id, v_request.status;
    END CASE;
  ELSE
    IF v_request.status NOT IN ('PENDING'::public.leave_status, 'VALIDATED_DC'::public.leave_status, 'VALIDATED_RP'::public.leave_status) THEN
      RAISE EXCEPTION 'La demande de mission #% est au statut %, elle ne peut pas etre rejetee',
        p_request_id, v_request.status;
    END IF;
  END IF;

  UPDATE mission_requests SET
    status = 'REJECTED'::public.leave_status,
    rejected_by = p_rejector_id,
    rejected_at = NOW(),
    rejection_reason = TRIM(p_reason),
    director_decision = CASE
      WHEN v_rejector.role::TEXT IN ('DIRECTEUR_EXECUTIF', 'ADMIN') THEN 'REFUSEE'
      ELSE director_decision
    END,
    updated_at = NOW()
  WHERE id = p_request_id;

  RETURN (SELECT to_jsonb(mr.*) FROM mission_requests mr WHERE mr.id = p_request_id);
END;
$$;


-- ── UNDO APPROVE MISSION ──
CREATE OR REPLACE FUNCTION public.undo_approve_mission_request(
  p_request_id BIGINT,
  p_user_id    UUID
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_request      mission_requests%ROWTYPE;
  v_user         utilisateurs%ROWTYPE;
  v_prev_status  TEXT;
  v_field        TEXT;
BEGIN
  SELECT * INTO v_request FROM mission_requests WHERE id = p_request_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Demande de mission #% introuvable', p_request_id;
  END IF;

  SELECT * INTO v_user FROM utilisateurs WHERE id = p_user_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Utilisateur introuvable';
  END IF;

  IF v_request.status = v_request.initial_status THEN
    RAISE EXCEPTION 'Impossible d''annuler: la demande est a son statut initial';
  END IF;

  CASE v_request.status
    WHEN 'VALIDATED_DC'::public.leave_status THEN
      v_prev_status := 'PENDING';
      v_field := 'dc';
      IF v_user.role::TEXT != 'ADMIN' AND v_request.approved_by_dc != p_user_id THEN
        RAISE EXCEPTION 'Seul l''approbateur ou un admin peut annuler cette validation';
      END IF;
      IF v_request.initial_status = 'VALIDATED_DC'::public.leave_status THEN
        RAISE EXCEPTION 'Impossible d''annuler: la demande est a son statut initial';
      END IF;
    WHEN 'VALIDATED_RP'::public.leave_status THEN
      v_prev_status := 'VALIDATED_DC';
      v_field := 'rp';
      IF v_user.role::TEXT != 'ADMIN' AND v_request.approved_by_rp != p_user_id THEN
        RAISE EXCEPTION 'Seul l''approbateur ou un admin peut annuler cette validation';
      END IF;
      IF v_request.initial_status = 'VALIDATED_RP'::public.leave_status THEN
        RAISE EXCEPTION 'Impossible d''annuler: la demande est a son statut initial';
      END IF;
    WHEN 'APPROVED'::public.leave_status THEN
      v_prev_status := 'VALIDATED_RP';
      v_field := 'de';
      IF v_user.role::TEXT != 'ADMIN' AND v_request.approved_by_de != p_user_id THEN
        RAISE EXCEPTION 'Seul l''approbateur ou un admin peut annuler cette validation';
      END IF;
      UPDATE mission_requests SET director_decision = NULL WHERE id = p_request_id;
    ELSE
      RAISE EXCEPTION 'La demande de mission #% est au statut %, impossible d''annuler',
        p_request_id, v_request.status;
  END CASE;

  EXECUTE format(
    'UPDATE mission_requests SET status = $1::public.leave_status, approved_by_%s = NULL, approved_at_%s = NULL, updated_at = NOW() WHERE id = $2',
    v_field, v_field
  ) USING v_prev_status, p_request_id;

  RETURN (SELECT to_jsonb(mr.*) FROM mission_requests mr WHERE mr.id = p_request_id);
END;
$$;


-- ── UNDO REJECT MISSION ──
CREATE OR REPLACE FUNCTION public.undo_reject_mission_request(
  p_request_id BIGINT,
  p_user_id    UUID
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_request        mission_requests%ROWTYPE;
  v_user           utilisateurs%ROWTYPE;
  v_restore_status TEXT;
BEGIN
  SELECT * INTO v_request FROM mission_requests WHERE id = p_request_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Demande de mission #% introuvable', p_request_id;
  END IF;

  IF v_request.status != 'REJECTED'::public.leave_status THEN
    RAISE EXCEPTION 'La demande de mission #% n''est pas rejetee', p_request_id;
  END IF;

  SELECT * INTO v_user FROM utilisateurs WHERE id = p_user_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Utilisateur introuvable';
  END IF;

  IF v_user.role::TEXT != 'ADMIN' AND v_request.rejected_by != p_user_id THEN
    RAISE EXCEPTION 'Seul la personne qui a rejete ou un admin peut restaurer cette demande';
  END IF;

  IF v_request.approved_by_rp IS NOT NULL THEN
    v_restore_status := 'VALIDATED_RP';
  ELSIF v_request.approved_by_dc IS NOT NULL THEN
    v_restore_status := 'VALIDATED_DC';
  ELSE
    v_restore_status := 'PENDING';
  END IF;

  IF v_restore_status = 'PENDING' AND v_request.initial_status != 'PENDING'::public.leave_status THEN
    v_restore_status := v_request.initial_status::TEXT;
  ELSIF v_restore_status = 'VALIDATED_DC'
        AND v_request.initial_status IN ('VALIDATED_RP'::public.leave_status, 'APPROVED'::public.leave_status) THEN
    v_restore_status := v_request.initial_status::TEXT;
  END IF;

  UPDATE mission_requests SET
    status = v_restore_status::public.leave_status,
    rejected_by = NULL,
    rejected_at = NULL,
    rejection_reason = NULL,
    director_decision = NULL,
    updated_at = NOW()
  WHERE id = p_request_id;

  RETURN (SELECT to_jsonb(mr.*) FROM mission_requests mr WHERE mr.id = p_request_id);
END;
$$;


-- ==============================================================================
-- SECTION 9: MOROCCAN LABOR LAW RPCs
-- ==============================================================================

-- ── count_working_days ──
-- Counts working days between two dates, excluding non-working days and holidays
CREATE OR REPLACE FUNCTION count_working_days(
  p_start_date DATE,
  p_end_date   DATE,
  p_company_id BIGINT DEFAULT NULL
)
RETURNS INTEGER
LANGUAGE plpgsql
STABLE
AS $$
DECLARE
  v_count      INTEGER := 0;
  v_current    DATE := p_start_date;
  v_dow        INTEGER;
  v_company    BIGINT;
  v_is_holiday BOOLEAN;
  v_wd         RECORD;
  v_day_active BOOLEAN;
BEGIN
  v_company := COALESCE(p_company_id, (SELECT id FROM public.companies LIMIT 1));

  SELECT * INTO v_wd FROM public.working_days WHERE company_id = v_company LIMIT 1;

  IF NOT FOUND THEN
    v_wd.monday    := true;
    v_wd.tuesday   := true;
    v_wd.wednesday := true;
    v_wd.thursday  := true;
    v_wd.friday    := true;
    v_wd.saturday  := true;
    v_wd.sunday    := false;
  END IF;

  WHILE v_current <= p_end_date LOOP
    v_dow := EXTRACT(ISODOW FROM v_current)::INTEGER;

    v_day_active := CASE v_dow
      WHEN 1 THEN v_wd.monday
      WHEN 2 THEN v_wd.tuesday
      WHEN 3 THEN v_wd.wednesday
      WHEN 4 THEN v_wd.thursday
      WHEN 5 THEN v_wd.friday
      WHEN 6 THEN v_wd.saturday
      WHEN 7 THEN v_wd.sunday
      ELSE false
    END;

    IF v_day_active THEN
      SELECT EXISTS(
        SELECT 1 FROM public.holidays h
        WHERE h.company_id = v_company
        AND (
          (h.is_recurring = true
           AND EXTRACT(MONTH FROM h.date) = EXTRACT(MONTH FROM v_current)
           AND EXTRACT(DAY FROM h.date) = EXTRACT(DAY FROM v_current))
          OR
          (h.is_recurring = false AND h.date = v_current)
        )
      ) INTO v_is_holiday;

      IF NOT v_is_holiday THEN
        v_count := v_count + 1;
      END IF;
    END IF;

    v_current := v_current + 1;
  END LOOP;

  RETURN v_count;
END;
$$;


-- ── calculate_annual_entitlement ──
-- Moroccan law: 18 jours ouvrables/year + 1.5 days per 5-year seniority, max 30
CREATE OR REPLACE FUNCTION calculate_annual_entitlement(p_user_id UUID)
RETURNS JSONB
LANGUAGE plpgsql
STABLE
AS $$
DECLARE
  v_user              utilisateurs%ROWTYPE;
  v_hire_date         DATE;
  v_years_of_service  FLOAT;
  v_seniority_periods INTEGER;
  v_base_days         FLOAT := 18.0;
  v_bonus_days        FLOAT := 0;
  v_total_entitlement FLOAT;
  v_max_days          FLOAT := 30.0;
  v_is_minor          BOOLEAN := false;
BEGIN
  SELECT * INTO v_user FROM utilisateurs WHERE id = p_user_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'User % not found', p_user_id;
  END IF;

  v_hire_date := COALESCE(v_user.hire_date, CURRENT_DATE);

  IF v_user.birth_date IS NOT NULL THEN
    v_is_minor := (age(CURRENT_DATE, v_user.birth_date) < interval '18 years');
  END IF;

  IF v_is_minor THEN
    v_base_days := 24.0;
  END IF;

  v_years_of_service := EXTRACT(EPOCH FROM age(CURRENT_DATE, v_hire_date)) / (365.25 * 86400);
  v_seniority_periods := FLOOR(v_years_of_service / 5.0)::INTEGER;
  v_bonus_days := v_seniority_periods * 1.5;
  v_total_entitlement := LEAST(v_base_days + v_bonus_days, v_max_days);

  RETURN jsonb_build_object(
    'user_id',            p_user_id,
    'hire_date',          v_hire_date,
    'years_of_service',   ROUND(v_years_of_service::NUMERIC, 1),
    'seniority_periods',  v_seniority_periods,
    'base_days',          v_base_days,
    'bonus_days',         v_bonus_days,
    'annual_entitlement', v_total_entitlement,
    'is_minor',           v_is_minor,
    'max_days',           v_max_days
  );
END;
$$;


-- ── calculate_leave_balance ──
-- Combines entitlement with actual usage for current year
CREATE OR REPLACE FUNCTION calculate_leave_balance(p_user_id UUID)
RETURNS JSONB
LANGUAGE plpgsql
STABLE
AS $$
DECLARE
  v_user                utilisateurs%ROWTYPE;
  v_entitlement         JSONB;
  v_annual_entitlement  FLOAT;
  v_current_year        INTEGER := EXTRACT(YEAR FROM CURRENT_DATE)::INTEGER;
  v_days_used_this_year FLOAT := 0;
  v_days_pending        FLOAT := 0;
  v_recup_used          FLOAT := 0;
  v_recup_pending       FLOAT := 0;
BEGIN
  SELECT * INTO v_user FROM utilisateurs WHERE id = p_user_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'User % not found', p_user_id;
  END IF;

  v_entitlement := calculate_annual_entitlement(p_user_id);
  v_annual_entitlement := (v_entitlement->>'annual_entitlement')::FLOAT;

  SELECT COALESCE(SUM(days_count), 0) INTO v_days_used_this_year
  FROM leave_requests
  WHERE user_id = p_user_id
    AND request_type = 'CONGE'
    AND status = 'APPROVED'
    AND EXTRACT(YEAR FROM start_date) = v_current_year;

  SELECT COALESCE(SUM(days_count), 0) INTO v_days_pending
  FROM leave_requests
  WHERE user_id = p_user_id
    AND request_type = 'CONGE'
    AND status IN ('PENDING', 'VALIDATED_RP', 'VALIDATED_DC')
    AND EXTRACT(YEAR FROM start_date) = v_current_year;

  SELECT COALESCE(SUM(days_count), 0) INTO v_recup_used
  FROM leave_requests
  WHERE user_id = p_user_id
    AND request_type = 'RECUPERATION'
    AND status = 'APPROVED'
    AND EXTRACT(YEAR FROM start_date) = v_current_year;

  SELECT COALESCE(SUM(days_count), 0) INTO v_recup_pending
  FROM leave_requests
  WHERE user_id = p_user_id
    AND request_type = 'RECUPERATION'
    AND status IN ('PENDING', 'VALIDATED_RP', 'VALIDATED_DC')
    AND EXTRACT(YEAR FROM start_date) = v_current_year;

  RETURN jsonb_build_object(
    'user_id',              p_user_id,
    'balance_conge',        v_user.balance_conge,
    'balance_recuperation', v_user.balance_recuperation,
    'annual_entitlement',   v_annual_entitlement,
    'days_used_this_year',  v_days_used_this_year,
    'days_pending',         v_days_pending,
    'recup_used',           v_recup_used,
    'recup_pending',        v_recup_pending,
    'entitlement_details',  v_entitlement
  );
END;
$$;


-- ── credit_recuperation ──
-- RH/Admin credits recuperation days when employee works on rest days
CREATE OR REPLACE FUNCTION credit_recuperation(
  p_user_id   UUID,
  p_days      FLOAT,
  p_date_from DATE,
  p_date_to   DATE,
  p_reason    TEXT
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_user        utilisateurs%ROWTYPE;
  v_new_balance FLOAT;
BEGIN
  SELECT * INTO v_user FROM utilisateurs WHERE id = p_user_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'User % not found', p_user_id;
  END IF;

  IF p_days <= 0 THEN
    RAISE EXCEPTION 'Days must be positive';
  END IF;

  v_new_balance := v_user.balance_recuperation + p_days;
  UPDATE utilisateurs SET balance_recuperation = v_new_balance WHERE id = p_user_id;

  INSERT INTO leave_balance_history (user_id, type, amount, reason, year, date_from, date_to)
  VALUES (
    p_user_id,
    'RECUPERATION',
    p_days,
    COALESCE(p_reason, 'Credit recuperation'),
    EXTRACT(YEAR FROM p_date_from)::INT,
    p_date_from,
    p_date_to
  );

  RETURN jsonb_build_object(
    'user_id',       p_user_id,
    'days_credited', p_days,
    'new_balance',   v_new_balance,
    'reason',        p_reason
  );
END;
$$;


-- ── recalculate_all_balances ──
-- Admin function to reset all balances from entitlement - usage
CREATE OR REPLACE FUNCTION recalculate_all_balances()
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_user         RECORD;
  v_entitlement  JSONB;
  v_annual       FLOAT;
  v_used         FLOAT;
  v_new_balance  FLOAT;
  v_current_year INTEGER := EXTRACT(YEAR FROM CURRENT_DATE)::INTEGER;
  v_count        INTEGER := 0;
BEGIN
  FOR v_user IN SELECT id, full_name FROM utilisateurs WHERE is_active = true LOOP
    v_entitlement := calculate_annual_entitlement(v_user.id);
    v_annual := (v_entitlement->>'annual_entitlement')::FLOAT;

    SELECT COALESCE(SUM(days_count), 0) INTO v_used
    FROM leave_requests
    WHERE user_id = v_user.id
      AND request_type = 'CONGE'
      AND status = 'APPROVED'
      AND EXTRACT(YEAR FROM start_date) = v_current_year;

    v_new_balance := GREATEST(v_annual - v_used, 0);

    UPDATE utilisateurs SET balance_conge = v_new_balance WHERE id = v_user.id;

    INSERT INTO leave_balance_history (user_id, type, amount, reason, year)
    VALUES (
      v_user.id,
      'CONGE',
      v_new_balance,
      'Recalcul automatique - Droit annuel ' || v_current_year,
      v_current_year
    );

    v_count := v_count + 1;
  END LOOP;

  RETURN jsonb_build_object(
    'employees_updated', v_count,
    'year',              v_current_year,
    'status',            'completed'
  );
END;
$$;


-- ==============================================================================
-- SECTION 10: BALANCE INIT RPC
-- ==============================================================================

-- Allows RH/ADMIN to manually set leave balance (for initial setup)
CREATE OR REPLACE FUNCTION set_initial_balance(
  p_user_id  UUID,
  p_balance  FLOAT,
  p_year     INTEGER,
  p_reason   TEXT DEFAULT 'Initialisation solde par RH'
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_user        utilisateurs%ROWTYPE;
  v_old_balance FLOAT;
BEGIN
  SELECT * INTO v_user FROM utilisateurs WHERE id = p_user_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Utilisateur % introuvable', p_user_id;
  END IF;

  IF p_balance < 0 THEN
    RAISE EXCEPTION 'Le solde ne peut pas etre negatif';
  END IF;

  v_old_balance := v_user.balance_conge;

  UPDATE utilisateurs
  SET balance_conge = p_balance, updated_at = NOW()
  WHERE id = p_user_id;

  INSERT INTO leave_balance_history (user_id, type, amount, reason, year)
  VALUES (
    p_user_id,
    'CONGE',
    p_balance,
    COALESCE(p_reason, 'Initialisation solde par RH') || ' (ancien solde: ' || v_old_balance || ')',
    p_year
  );

  RETURN jsonb_build_object(
    'user_id',     p_user_id,
    'old_balance', v_old_balance,
    'new_balance', p_balance,
    'year',        p_year
  );
END;
$$;


-- ==============================================================================
-- SECTION 11: GRANTS
-- ==============================================================================

GRANT EXECUTE ON FUNCTION public.get_my_role() TO authenticated, anon, service_role;
GRANT EXECUTE ON FUNCTION public.is_manager() TO authenticated, anon, service_role;
GRANT EXECUTE ON FUNCTION public.can_manage_user(UUID) TO authenticated, anon, service_role;

-- Leave RPCs
GRANT EXECUTE ON FUNCTION public.approve_leave_request(BIGINT, UUID, DATE, DATE, FLOAT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.reject_leave_request(BIGINT, UUID, TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.undo_approve_leave_request(BIGINT, UUID) TO authenticated;
GRANT EXECUTE ON FUNCTION public.undo_reject_leave_request(BIGINT, UUID) TO authenticated;

-- Mission RPCs
GRANT EXECUTE ON FUNCTION public.approve_mission_request(BIGINT, UUID) TO authenticated;
GRANT EXECUTE ON FUNCTION public.reject_mission_request(BIGINT, UUID, TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.undo_approve_mission_request(BIGINT, UUID) TO authenticated;
GRANT EXECUTE ON FUNCTION public.undo_reject_mission_request(BIGINT, UUID) TO authenticated;

-- Moroccan labor law RPCs
GRANT EXECUTE ON FUNCTION count_working_days TO authenticated;
GRANT EXECUTE ON FUNCTION calculate_annual_entitlement TO authenticated;
GRANT EXECUTE ON FUNCTION calculate_leave_balance TO authenticated;
GRANT EXECUTE ON FUNCTION credit_recuperation TO authenticated;
GRANT EXECUTE ON FUNCTION recalculate_all_balances TO authenticated;
GRANT EXECUTE ON FUNCTION set_initial_balance TO authenticated;


-- ==============================================================================
-- SECTION 12: SEED DATA (Working days + Moroccan public holidays)
-- ==============================================================================

-- Working days: Mon-Sat (Moroccan jours ouvrables default)
INSERT INTO public.working_days (company_id, monday, tuesday, wednesday, thursday, friday, saturday, sunday)
SELECT c.id, true, true, true, true, true, true, false
FROM public.companies c
WHERE NOT EXISTS (SELECT 1 FROM public.working_days w WHERE w.company_id = c.id);

-- Moroccan public holidays
DO $$
DECLARE
  v_company_id BIGINT;
BEGIN
  SELECT id INTO v_company_id FROM public.companies LIMIT 1;

  IF v_company_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM public.holidays WHERE company_id = v_company_id) THEN
    INSERT INTO public.holidays (company_id, name, date, is_recurring) VALUES
      -- Fixed national holidays (recurring)
      (v_company_id, 'Nouvel An',                         '2025-01-01', true),
      (v_company_id, 'Manifeste de l''Independance',      '2025-01-11', true),
      (v_company_id, 'Yennayer (Nouvel An Amazigh)',       '2025-01-14', true),
      (v_company_id, 'Fete du Travail',                    '2025-05-01', true),
      (v_company_id, 'Fete du Trone',                      '2025-07-30', true),
      (v_company_id, 'Allegeance Oued Ed-Dahab',           '2025-08-14', true),
      (v_company_id, 'Revolution du Roi et du Peuple',     '2025-08-20', true),
      (v_company_id, 'Fete de la Jeunesse',                '2025-08-21', true),
      (v_company_id, 'Fete de l''Unite',                   '2025-10-31', true),
      (v_company_id, 'Marche Verte',                       '2025-11-06', true),
      (v_company_id, 'Fete de l''Independance',            '2025-11-18', true),

      -- Religious holidays 2025 (Hijri calendar)
      (v_company_id, 'Aid Al-Fitr (1er jour)',            '2025-03-30', false),
      (v_company_id, 'Aid Al-Fitr (2eme jour)',           '2025-03-31', false),
      (v_company_id, 'Aid Al-Adha (1er jour)',            '2025-06-06', false),
      (v_company_id, 'Aid Al-Adha (2eme jour)',           '2025-06-07', false),
      (v_company_id, '1er Moharram',                       '2025-06-26', false),
      (v_company_id, 'Aid Al Mawlid (1er jour)',          '2025-09-04', false),
      (v_company_id, 'Aid Al Mawlid (2eme jour)',         '2025-09-05', false),

      -- Religious holidays 2026
      (v_company_id, 'Aid Al-Fitr (1er jour)',            '2026-03-20', false),
      (v_company_id, 'Aid Al-Fitr (2eme jour)',           '2026-03-21', false),
      (v_company_id, 'Aid Al-Adha (1er jour)',            '2026-05-27', false),
      (v_company_id, 'Aid Al-Adha (2eme jour)',           '2026-05-28', false),
      (v_company_id, '1er Moharram',                       '2026-06-16', false),
      (v_company_id, 'Aid Al Mawlid (1er jour)',          '2026-08-25', false),
      (v_company_id, 'Aid Al Mawlid (2eme jour)',         '2026-08-26', false),

      -- Religious holidays 2027
      (v_company_id, 'Aid Al-Fitr (1er jour)',            '2027-03-10', false),
      (v_company_id, 'Aid Al-Fitr (2eme jour)',           '2027-03-11', false),
      (v_company_id, 'Aid Al-Adha (1er jour)',            '2027-05-17', false),
      (v_company_id, 'Aid Al-Adha (2eme jour)',           '2027-05-18', false),
      (v_company_id, '1er Moharram',                       '2027-06-06', false),
      (v_company_id, 'Aid Al Mawlid (1er jour)',          '2027-08-14', false),
      (v_company_id, 'Aid Al Mawlid (2eme jour)',         '2027-08-15', false);
  END IF;
END $$;


-- ==============================================================================
-- SCHEMA COMPLETE
-- ==============================================================================
