-- ==============================================================================
-- COMPLETE CONGE MANAGEMENT MIGRATION - SIMPLIFIED VERSION
-- ==============================================================================
-- This version uses a standalone "utilisateurs" table instead of profiles+auth
-- ==============================================================================

-- ==============================================================================
-- STEP 1: CREATE ENUMS
-- ==============================================================================

DO $$ BEGIN
    CREATE TYPE public.leave_request_type AS ENUM ('CONGE', 'RECUPERATION');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE public.leave_status AS ENUM (
        'PENDING',
        'VALIDATED_DC',
        'VALIDATED_RP',
        'VALIDATED_TG',
        'VALIDATED_DE',
        'APPROVED',
        'REJECTED',
        'CANCELLED',
        'ARCHIVED'
    );
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE public.user_role AS ENUM (
        'EMPLOYEE',
        'CHEF_SERVICE',
        'RESPONSABLE_PERSONNEL',
        'TRESORIER_GENERAL',
        'DIRECTEUR_EXECUTIF',
        'ADMIN'
    );
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- ==============================================================================
-- STEP 2: CREATE CORE TABLES
-- ==============================================================================

-- Companies table
CREATE TABLE IF NOT EXISTS public.companies (
    id bigint generated by default as identity primary key,
    legacy_id text UNIQUE,
    name text NOT NULL UNIQUE,
    created_at timestamptz default now() not null,
    updated_at timestamptz default now() not null
);

-- Departments table
CREATE TABLE IF NOT EXISTS public.departments (
    id bigint generated by default as identity primary key,
    legacy_id bigint UNIQUE,
    name text NOT NULL,
    company_id bigint references public.companies(id) ON DELETE CASCADE,
    filter_budget text,
    filter_article text,
    created_at timestamptz default now() not null,
    updated_at timestamptz default now() not null
);

-- Utilisateurs table (standalone, no auth.users dependency)
CREATE TABLE IF NOT EXISTS public.utilisateurs (
    id uuid default gen_random_uuid() primary key,
    legacy_id bigint UNIQUE,
    email text UNIQUE,
    password_hash text,  -- Will store hashed passwords
    full_name text NOT NULL,
    username text UNIQUE,
    company_id bigint references public.companies(id),
    department_id bigint references public.departments(id),
    job_title text,
    role public.user_role default 'EMPLOYEE',
    is_active boolean default true,
    balance_conge float default 0,
    balance_recuperation float default 0,
    phone text,
    avatar_url text,
    hire_date date,
    birth_date date,
    matricule text,
    cin text,
    cnss text,
    rib text,
    address text,
    city text,
    gender text,
    legacy_profile_id int,
    is_signatory boolean default false,
    signatory_type text,
    signature_file text,
    last_login timestamptz,
    created_at timestamptz default now() not null,
    updated_at timestamptz default now() not null
);

-- ==============================================================================
-- STEP 3: CREATE SUPPORTING TABLES
-- ==============================================================================

-- Leave requests table
CREATE TABLE IF NOT EXISTS public.leave_requests (
    id bigint generated by default as identity primary key,
    legacy_id bigint UNIQUE,
    user_id uuid references public.utilisateurs(id) NOT NULL,
    request_type public.leave_request_type NOT NULL,
    start_date date NOT NULL,
    end_date date NOT NULL,
    days_count float NOT NULL,
    return_date date,
    replacement_user_id uuid references public.utilisateurs(id),
    status public.leave_status default 'PENDING',
    reason text,
    comments text,
    balance_before float,
    balance_conge_used float,
    balance_recuperation_used float,
    approved_by_dc uuid references public.utilisateurs(id),
    approved_by_rp uuid references public.utilisateurs(id),
    approved_by_tg uuid references public.utilisateurs(id),
    approved_by_de uuid references public.utilisateurs(id),
    approved_at_dc timestamptz,
    approved_at_rp timestamptz,
    approved_at_tg timestamptz,
    approved_at_de timestamptz,
    rejected_by uuid references public.utilisateurs(id),
    rejected_at timestamptz,
    rejection_reason text,
    created_at timestamptz default now() not null,
    updated_at timestamptz default now() not null
);

-- Leave balance history
CREATE TABLE IF NOT EXISTS public.leave_balance_history (
    id bigint generated by default as identity primary key,
    user_id uuid references public.utilisateurs(id) NOT NULL,
    type public.leave_request_type NOT NULL,
    amount float NOT NULL,
    reason text,
    year int,
    date_from date,
    date_to date,
    created_at timestamptz default now() not null
);

-- Working days configuration
CREATE TABLE IF NOT EXISTS public.working_days (
    id bigint generated by default as identity primary key,
    company_id bigint references public.companies(id),
    monday boolean default true,
    tuesday boolean default true,
    wednesday boolean default true,
    thursday boolean default true,
    friday boolean default true,
    saturday boolean default false,
    sunday boolean default false
);

-- Holidays
CREATE TABLE IF NOT EXISTS public.holidays (
    id bigint generated by default as identity primary key,
    company_id bigint references public.companies(id),
    name text NOT NULL,
    date date NOT NULL,
    is_recurring boolean default false,
    created_at timestamptz default now() not null
);

-- Notifications
CREATE TABLE IF NOT EXISTS public.notifications (
    id bigint generated by default as identity primary key,
    user_id uuid references public.utilisateurs(id) NOT NULL,
    title text NOT NULL,
    message text NOT NULL,
    type text,
    related_request_id bigint references public.leave_requests(id),
    is_read boolean default false,
    created_at timestamptz default now() not null
);

-- Audit logs
CREATE TABLE IF NOT EXISTS public.audit_logs (
    id bigint generated by default as identity primary key,
    table_name text NOT NULL,
    record_id bigint,
    action text NOT NULL,
    old_data jsonb,
    new_data jsonb,
    user_id uuid references public.utilisateurs(id),
    created_at timestamptz default now() not null
);

-- ==============================================================================
-- STEP 4: CREATE INDEXES
-- ==============================================================================

CREATE INDEX IF NOT EXISTS idx_utilisateurs_company ON public.utilisateurs(company_id);
CREATE INDEX IF NOT EXISTS idx_utilisateurs_department ON public.utilisateurs(department_id);
CREATE INDEX IF NOT EXISTS idx_utilisateurs_role ON public.utilisateurs(role);
CREATE INDEX IF NOT EXISTS idx_utilisateurs_legacy_id ON public.utilisateurs(legacy_id);
CREATE INDEX IF NOT EXISTS idx_utilisateurs_email ON public.utilisateurs(email);
CREATE INDEX IF NOT EXISTS idx_leave_requests_user ON public.leave_requests(user_id);
CREATE INDEX IF NOT EXISTS idx_leave_requests_status ON public.leave_requests(status);
CREATE INDEX IF NOT EXISTS idx_leave_requests_dates ON public.leave_requests(start_date, end_date);
CREATE INDEX IF NOT EXISTS idx_notifications_user ON public.notifications(user_id, is_read);
CREATE INDEX IF NOT EXISTS idx_departments_legacy_id ON public.departments(legacy_id);

-- ==============================================================================
-- STEP 5: INSERT INITIAL DATA (Companies & Departments)
-- ==============================================================================

-- Insert companies
INSERT INTO public.companies (legacy_id, name) VALUES
('1', 'ATH'),
('2', 'TH2')
ON CONFLICT (legacy_id) DO NOTHING;

-- Insert departments
INSERT INTO public.departments (legacy_id, name, company_id, filter_budget, filter_article)
SELECT 
    d.id::bigint,
    d.designation,
    c.id,
    d.filtreBudget,
    d.filtreArticle
FROM (VALUES
    (3, 'Production', 'PRO-;REC', 'PROD;RECA', '1'),
    (5, 'Partenariat', 'P&P-;REC-', 'PROT;RECA', '1'),
    (6, 'Logistique', 'LOG;FON-13005;REC', 'LOGI;262FONC;263FONC;265FONC;266FONC;RECA', '1'),
    (8, 'Communication', 'COM-', 'COMM', '1'),
    (9, 'Sportif', 'SPO-;DOT-', 'SPOR;DOTA', '1'),
    (11, 'ADMINISTRATIF & FINANCE', '', '', '1'),
    (14, 'Fonctionnement', 'FON-;PRO-', 'FONC;PROD', '1'),
    (19, 'SPORTIF TH II', 'SPO-;DOT-', 'SPOR;DOTA', '1'),
    (15, 'Sécurité', 'SEC-', 'SECU', '1'),
    (16, 'Hébergement', 'LOG-;REC-', 'LOGI;RECA', '1'),
    (17, 'ACCREDITATION', 'LOG-', 'LOGI', '1'),
    (18, 'Restauration', 'LOG-', 'LOGI', '1'),
    (20, 'PRODUCTION CDT', 'PRO-;SEC-;REC', 'PROD;SECU;RECA', '1'),
    (21, 'ADMINISTRATIF', '', '', '1'),
    (22, 'Financier', '', '', '1'),
    (23, 'RECEPTION & ANIMATION', 'REC', 'RECA', '1')
) AS d(id, designation, filtreBudget, filtreArticle, idSociete)
LEFT JOIN public.companies c ON c.legacy_id = d.idSociete
ON CONFLICT (legacy_id) DO NOTHING;

-- ==============================================================================
-- STEP 6: CREATE HELPER FUNCTIONS FOR USER MIGRATION
-- ==============================================================================

-- Function to map legacy profile to new role
CREATE OR REPLACE FUNCTION map_legacy_profile_to_role(legacy_profile INT)
RETURNS public.user_role AS $$
BEGIN
    RETURN CASE 
        WHEN legacy_profile IN (1, 16) THEN 'ADMIN'::public.user_role
        WHEN legacy_profile IN (9, 11) THEN 'RESPONSABLE_PERSONNEL'::public.user_role
        WHEN legacy_profile IN (12, 13, 15) THEN 'CHEF_SERVICE'::public.user_role
        ELSE 'EMPLOYEE'::public.user_role
    END;
END;
$$ LANGUAGE plpgsql;

-- Function to map legacy status
CREATE OR REPLACE FUNCTION map_legacy_status(legacy_status TEXT)
RETURNS public.leave_status AS $$
BEGIN
    RETURN CASE 
        WHEN legacy_status = 'Encours' THEN 'PENDING'::public.leave_status
        WHEN legacy_status = 'Valide DC' THEN 'VALIDATED_DC'::public.leave_status
        WHEN legacy_status = 'Valide RP' THEN 'VALIDATED_RP'::public.leave_status
        WHEN legacy_status = 'Valide TG' THEN 'VALIDATED_TG'::public.leave_status
        WHEN legacy_status = 'Valide DE' THEN 'VALIDATED_DE'::public.leave_status
        ELSE 'PENDING'::public.leave_status
    END;
END;
$$ LANGUAGE plpgsql;

-- Function to hash password (simple crypt for now)
CREATE OR REPLACE FUNCTION hash_password(plain_password TEXT)
RETURNS TEXT AS $$
BEGIN
    -- Using crypt extension for password hashing
    RETURN crypt(plain_password, gen_salt('bf', 8));
END;
$$ LANGUAGE plpgsql;

-- ==============================================================================
-- STEP 7: INSERT USERS (47 users from legacy database)
-- ==============================================================================

INSERT INTO public.utilisateurs (
    legacy_id, email, password_hash, full_name, username, company_id, department_id,
    job_title, role, is_active, phone, hire_date, birth_date,
    matricule, cin, cnss, rib, address, city, gender,
    legacy_profile_id, is_signatory, signatory_type, signature_file
)
SELECT
    u.id as legacy_id,
    COALESCE(NULLIF(u.email, ''), u.login || '@ath.ma') as email,
    hash_password(u.mot_passe) as password_hash,
    u.nom as full_name,
    u.login as username,
    (SELECT id FROM public.companies WHERE legacy_id = u.idSociete::text LIMIT 1) as company_id,
    (SELECT id FROM public.departments WHERE legacy_id = u.idDepartement LIMIT 1) as department_id,
    u.fonction as job_title,
    map_legacy_profile_to_role(u.profile) as role,
    CASE WHEN u.desactive = 0 THEN true ELSE false END as is_active,
    NULLIF(u.gsm, '') as phone,
    CASE WHEN u.dateEmbauche = '0000-00-00' OR u.dateEmbauche = '' THEN NULL ELSE u.dateEmbauche::date END as hire_date,
    CASE WHEN u.dateNaissance = '0000-00-00' OR u.dateNaissance = '' THEN NULL ELSE u.dateNaissance::date END as birth_date,
    NULLIF(u.matricule, '') as matricule,
    NULLIF(u.cin, '') as cin,
    NULLIF(u.cnss, '') as cnss,
    NULLIF(u.RIB, '') as rib,
    NULLIF(u.adresse, '') as address,
    NULLIF(u.ville, '') as city,
    CASE WHEN u.civilite = 'M' THEN 'M' WHEN u.civilite = 'Mme' THEN 'F' ELSE 'M' END as gender,
    u.profile as legacy_profile_id,
    CASE WHEN u.signataire != '' THEN true ELSE false END as is_signatory,
    NULLIF(u.signataire, '') as signatory_type,
    NULLIF(u.fichier_signature, '') as signature_file
FROM (VALUES
    (1, 5, 1, 'Administrateur', 'admin', 'Hiko1970', 1, 'controle.gestion@ath.ma', 1, 0, '', 'Directeur exécutif', 1, '11111', 1, 0, 0, '', '17171717171', '01TEST', '0661101010', '2001-12-10', '2026-01-23', 'test', 'M', 'BE101010', '', 'Casablanca', 'sinature.png'),
    (7, 8, 3, 'OTHMAN SERGHINI', 'o.serghini', 'Oth/2023#', 2, 'othman.serghini@ath.ma', 1, 0, '', 'Chef de Projet Marketing TV', 0, '11111', 0, 20, 58, '', '1111111111111111111', 'test etst test ', '000000000', '1989-02-10', '2012-06-22', 'HEHEHH13', 'M', 'BE1223545', '', '', 'signature.png'),
    (10, 11, 1, 'MOHAMED IRAQI', 'iraqi', '123456', 9, 'mohamed.iraqi@ath.ma', 1, 0, 'de', 'DIRECTEUR EXECUTIF', 1, 'YCDYS', 1, 8, 0, '', '', '', '', '0000-00-00', '', '', 'M', '', '', '', 'iraqi.png'),
    (55, 14, 3, 'MOUNIR EL KHOLTY', 'm.elkholty', 'mounirmaestro2025', 2, 'mounir.elkholty@ath.ma', 1, 0, '', 'Gestionnaire de stock', 0, 'BHXLM', 0, 11, 0, '', '', '', '', '0000-00-00', '', '', 'M', '', '', '', 'elkholty.png'),
    (56, 11, 0, 'NAOUFEL  BENSOUDA', 'bensouda', 'Bensouda/23!!', 11, 'capitaleexpertise1@gmail.com', 1, 0, 'tg', 'Directeur Financier', 1, '4DCVO', 1, 12, 0, '', '', '', '', '0000-00-00', '', '', 'M', '', '', '', 'bensouda.png'),
    (57, 22, 0, 'HOUDA EL MAAROUFI', 'h.elmaaroufi', 'Houda2023@', 1, 'houda.elmaaroufi@gmail.com', 1, 0, '', 'Responsable Financier', 0, '11111', 1, 8, 83, '', '', '', '', '0000-00-00', '', '', 'M', '', '', '', 'signature.png'),
    (58, 8, 2, 'MOUNIA EL KHETTAR ', 'm.elkhattar', 'Ayaadam0811', 12, 'm.elkhettar@frmg.ma', 1, 0, '', 'Directrice Communication', 0, '2QPVS', 1, 20, 58, '', '', '', '', '0000-00-00', '', '', 'M', '', '', '', 'elkhettar.png'),
    (59, 11, 3, 'MERYEM HANINE', 'm.hanine', 'Meryem2023@', 3, 'meryem.hanine@ath.ma', 1, 0, '', 'Cadre Administratif et Comptable', 0, '11111', 1, 10, 0, '', '', '', '', '0000-00-00', '', '', 'M', '', '', '', 'hanine.png'),
    (60, 8, 3, 'NADA ATOUANI', 'n.atouani', 'N#2023', 2, 'nada.atouani@ath.ma', 1, 0, '', 'Infographiste', 0, '', 0, 20, 58, '', '', '', '', '0000-00-00', '', '', 'M', '', '', '', 'signature.png'),
    (61, 8, 3, 'RITA BENNAGHMOUCH', 'r.bennaghmouch', 'Rita@2023', 2, 'rita.bennaghmouch@ath.ma', 1, 0, '', 'Responsable Communication Événementiel', 0, '', 0, 20, 58, '', '', '', '', '0000-00-00', '', '', 'M', '', '', '', 'signature.png'),
    (62, 14, 0, 'HIND ENNAFIS', 'h.ennafis', 'hind@2020', 12, '', 1, 1, '', 'Responsable Administratif', 0, 'AP278', 0, 1, 62, '', '', '', '', '0000-00-00', '', '', 'M', '', '', '', 'ennafis.png'),
    (63, 6, 3, 'BLANDINE CHARBONNEL', 'b.charbonnel', 'Bl@nde!', 12, 'blandine.charbonnel@ath.ma', 1, 0, '', 'Responsable Logistique', 0, 'FQAGG', 1, 5, 63, '', '', '', '', '0000-00-00', '', '', 'M', '', '', '', 'charbounnel.png'),
    (64, 16, 0, 'SOUAD REGRAGUI', 's.regragui', 'Souad/23!', 13, 'logistique@ath.ma', 1, 0, '', 'Responsable Hébergement, Aérien et Transport Terrestre', 0, '0U48C', 1, 22, 64, '', '', '', '', '0000-00-00', '', '', 'M', '', '', '', 'regragui.png'),
    (65, 17, 0, 'NAOUFEL EL MAAROUFI', 'n.elmaaroufi', 'Naoufel23#', 13, 'nawfal@ttevents.ma', 1, 0, '', 'Respnsable Accréditation et Contôle d''accès', 0, 'W3BSC', 1, 23, 65, '', '', '', '', '0000-00-00', '', '', 'M', '', '', '', 'n.elmaaroufi.png'),
    (66, 18, 0, 'MERYEM BECHARI', 'm.bechari', 'Meryem/23@', 13, 'restauration@ath.ma', 1, 0, '', 'Responsable Restauration', 0, '91VXZ', 1, 21, 66, '', '', '', '', '0000-00-00', '', '', 'M', '', '', '', 'bechari.png'),
    (67, 17, 1, 'YASSINE CHARAI', 'y.charai', 'Yassine2023', 13, 'ycharai@yahoo.fr', 1, 1, '', 'Responsable Production', 0, 'RU0GG', 1, 15, 67, '', '', '', '', '0000-00-00', '', '', 'M', '', '', '', 'charai.png'),
    (68, 5, 3, 'RIME ZAKI', 'r.zaki', 'Rime23/', 2, 'rime.zaki@ath.ma', 1, 0, '', 'Responsable Protocole et Partenariat', 0, 'AIEE2', 1, 18, 69, '', '', '', '', '0000-00-00', '', '', 'M', '', '', '', 'zaki.png'),
    (69, 5, 2, 'FATIMA ZAHRA EL ATLASSI', 'f.elatlassi', 'Fati/23#', 12, 'f.elatlassi@ath.ma', 1, 0, '', 'Directrice Protocole et Partenariat', 0, 'W3LQU', 1, 18, 69, '', '', '', '', '0000-00-00', '', '', 'M', '', '', '', 'atlassi.png'),
    (70, 5, 3, 'FATIME ZAHRA EL ALAOUI', 'f.elalaoui', '123456', 2, 'fatimazahra.elalaoui@ath.ma', 1, 0, '', 'Coordinatrice Protocole et Partenariat', 0, '', 0, 18, 69, '', '', '', '', '0000-00-00', '', '', 'M', '', '', '', 'signature.png'),
    (71, 15, 3, 'Didier DELMAS', 'securite', 'Secu/23#', 13, 'delmasdidier01@gmail.com', 1, 0, '', 'Responsable Sécurité', 0, '8VXZF', 1, 25, 71, '', '', '', '', '0000-00-00', '', '', 'M', '', '', '', 'delmas.png'),
    (72, 9, 3, 'MOUNYA AMALOU', 'm.amalou', 'Mounya1969', 12, 'mounya.amalou@ath.ma', 1, 0, '', 'Directrice Sportive', 0, '4SCX7', 1, 3, 72, '', '', '', '', '0000-00-00', '', '', 'M', '', '', '', 'amalou.png'),
    (73, 9, 3, 'DRISS AGNAOU', 'd.agnaou', 'Driss@23', 2, 'driss.agnaou@ath.ma', 1, 0, '', 'Secrétaire Sportif', 0, '', 0, 3, 72, '', '', '', '', '0000-00-00', '', '', 'M', '', '', '', 'signature.png'),
    (74, 9, 3, 'KAMAL EL ASSALI', 'k.elassali', 'Kamal2023/', 2, 'kamal.elassali@ath.ma', 1, 0, '', 'Régisseur Sportif', 0, '', 0, 3, 72, '', '', '', '', '0000-00-00', '', '', 'M', '', '', '', 'signature.png'),
    (75, 11, 2, 'MICHEL BESANCENEY', 'MICHEL', '123456', 12, '', 1, 0, '', 'COORDONNATEUR DES EVENEMENTS INTERNATIONAUX', 0, '', 0, 0, 0, '', '', '', '', '0000-00-00', '', '', 'M', '', '', '', ''),
    (76, 16, 3, 'HAMZA EL YOUBI', 'Hamza', 'H2023amza', 14, '', 1, 1, '', 'ASSISTANT RESPONSABLE HEBERGEMENT', 0, '', 0, 22, 64, '', '', '', '', '0000-00-00', '', '', 'M', '', '', '', ''),
    (77, 19, 3, 'ABDELLATIF EL BACHARI', 'A.ELBACHARI', 'Bachari@2023', 13, 'aelbachari@yahoo.fr', 1, 0, '', 'Responsable Sportif TH II', 0, 'R73KW', 1, 24, 77, '', '', '', '', '0000-00-00', '', '', 'M', '', '', '', 'bachari.png'),
    (78, 19, 3, 'Driss Trophée', 'D.trophee', 'Driss@thII2023', 14, 'd.trophee@ath.ma', 1, 0, '', 'Secrétaire sportif ', 0, '', 0, 0, 77, '', '', '', '', '0000-00-00', '', '', 'M', '', '', '', ''),
    (79, 16, 0, 'KENZA TAZI', 'KENZA ', 'Kenza@24', 14, '', 1, 1, '', 'ASSISTANT RESPONSABLE HEBERGEMENT', 0, '', 0, 22, 64, '', '', '', '', '0000-00-00', '', '', 'M', '', '', '', ''),
    (80, 16, 0, 'OUMAIMA FANINE', 'OUMAIMA', 'Oumaima@24', 14, '', 1, 1, '', 'ASSISTANT RESPONSABLE HEBERGEMENT', 0, '', 0, 22, 64, '', '', '', '', '0000-00-00', '', '', 'M', '', '', '', ''),
    (81, 20, 0, 'AMINE RHARDA', 'r.amine', 'AM@cdt', 15, 'aminrharda2@gmail.com', 1, 0, '', 'Responsable Production ', 0, 'JZ5BS', 1, 26, 81, '', '', '', '', '0000-00-00', '', '', 'M', '', '', '', 'rharda.png'),
    (82, 21, 0, 'IBTISSAM CHERKAOUI ', 'IB.Cherkaoui', 'K2024Oui', 16, 'ibtissam.cherkaoui@ath.ma', 1, 0, '', 'Cadre Administratif', 0, '', 0, 0, 84, '', '', '', '', '0000-00-00', '', '', 'M', '', '', '', ''),
    (83, 14, 0, 'Intérim Responsable Administratif', 'Intérim.RA', '123456', 12, 'interim.ra@ath.ma', 1, 1, '', 'RESPONSABLE ADMINISTRATIF PAR INTERIM', 0, '9JUK1', 0, 8, 83, '', '', '', '', '0000-00-00', '', '', 'M', '', '', '', 'interime.png'),
    (84, 14, 0, 'MOUNA DAOUDI', 'M.Daoudi', 'moneta@96', 12, 'mouna.daoudi@ath.ma', 1, 0, '', 'Responsable Administrative ', 0, 'S82Q7', 1, 27, 84, '', '', '', '', '0000-00-00', '', '', 'M', '', '', '', 'daoudi.png'),
    (85, 14, 0, 'FOUZIA EL JAOUAL', 'F.Fouzia', '123456', 2, 'fouziaelja@gmail.com', 1, 1, '', 'Cadre Administratif', 0, '', 0, 27, 84, '', '', '', '', '0000-00-00', '', '', 'M', '', '', '', ''),
    (87, 14, 0, 'HAFID EDDAHBI', 'H.Eddahbi', '123456', 2, 'h.eddahbi@frmg.ma', 1, 0, '', 'Cadre Administratif', 0, '', 0, 27, 84, '', '', '', '', '0000-00-00', '', '', 'M', '', '', '', ''),
    (88, 14, 2, 'JIHANE MESSAHO', 'j.messaho', '123456', 2, '', 1, 0, '', 'Chargée de Mission auprès Cabinet de SAR le Prince Moulay RACHID', 0, '', 0, 0, 0, '', '', '', '', '0000-00-00', '', '', 'M', '', '', '', ''),
    (89, 23, 3, 'MARYEM ALAOUI', 'M.Alaoui', '987654', 13, 'm.alaoui@frmg.ma', 1, 0, '', 'Coordinatrice DTN', 0, '', 1, 28, 89, '', '', '', '', '0000-00-00', '', '', 'M', '', '', '', ''),
    (90, 9, 3, 'YOUSSEF JABAIRI', 'youssef', '123456', 2, 'y.jabairi@frmg.ma', 1, 0, '', 'Coordonateur  Sportif', 0, '', 0, 3, 0, '', '', '', '', '0000-00-00', '', '', 'M', '', '', '', ''),
    (91, 16, 4, 'MAMOUNE KADIRI', 'As.log', '456123', 14, 'assistlog@ath.ma', 1, 0, '', 'Assitant Logistique', 0, '', 0, 22, 64, '', '', '', '', '0000-00-00', '', '', 'M', '', '', '', ''),
    (92, 9, 3, 'KAMAL MOURI BENSOUDA', 'KAMAL', '123456', 2, 'bensoukamal@gmail.com', 1, 0, '', 'Assistant Sportif', 0, '', 0, 0, 0, '', '', '', '', '0000-00-00', '', '', 'M', '', '', '', ''),
    (93, 15, 3, 'FRANCK LEGRAND', 'FRANK', '123456', 13, 'securite@ath.ma', 1, 0, '', 'responsable Securite', 0, '', 0, 25, 0, '', '', '', '', '0000-00-00', '', '', 'M', '', '', '', ''),
    (94, 9, 3, 'MEHDI JABRANE', 'M.MEHDI', '123456', 2, 'mehdi.jabrane@ath.ma', 1, 0, '', 'CADRE SPORTIF', 0, '', 0, 0, 0, '', '', '', '', '0000-00-00', '', '', 'M', '', '', '', ''),
    (95, 6, 4, 'SORAYA DJEDIDI ', 'D.Soraya', '789456', 2, 'soraya.djedidi@ath.ma', 1, 0, '', 'Assistante logistique', 0, '', 0, 5, 63, '', '', '', '', '0000-00-00', '', '', 'M', '', '', '', ''),
    (96, 6, 4, 'MARIYAM OUALAYAD', 'M.oulayad', '456123', 2, 'mariyam.oualayad@gmail.com', 1, 0, '', 'Assistante logistique', 0, '', 0, 5, 63, '', '', '', '', '0000-00-00', '', '', 'M', '', '', '', ''),
    (97, 6, 4, 'Ghizlane KADIRI', 'G.Kadiri', '789632', 2, 'hebergement@ath.ma', 1, 0, '', 'Assistante logistique', 0, '', 0, 5, 0, '', '', '', '', '0000-00-00', '', '', 'M', '', '', '', ''),
    (102, 21, 2, 'ANAS ELYOUNSSI', '', '', 1, 'anaselyounssi2001@gmail.com', 1, 0, '', 'TEST FONCTION 2', 0, '', 0, 0, 0, '', '23247983479', 'TEST2 ANAS', '07070707070', '2001-12-10', '2014-07-16', 'TEEXTCNSS2', 'M', 'BE101010', '', '', '')
) AS u(id, idDepartement, idCategoriePersonnel, nom, login, mot_passe, profile, email, idSociete, desactive, signataire, fonction, validation, code_signature, histo, collaborateur, responsable, signerParResp, RIB, matricule, gsm, dateNaissance, dateEmbauche, cnss, civilite, cin, adresse, ville, fichier_signature)
ON CONFLICT (legacy_id) DO NOTHING;

-- ==============================================================================
-- STEP 8: CALCULATE LEAVE BALANCES
-- ==============================================================================

-- Calculate CONGE balance
UPDATE public.utilisateurs p
SET balance_conge = (
    SELECT COALESCE(SUM(sc.nbr_jours), 0)
    FROM (VALUES
        (24, 7, 'CONGE', 2022, NULL, NULL, 'Congé annuel', 12.00),
        (25, 7, 'CONGE', 2023, NULL, NULL, 'Congé annuel', 12.00),
        (26, 7, 'CONGE', 2024, NULL, NULL, 'Congé annuel', 12.00),
        (27, 7, 'CONGE', 2025, NULL, NULL, 'Congé annuel', 12.00),
        (28, 7, 'CONGE', 2026, NULL, NULL, 'Congé annuel', 12.00),
        (29, 1, 'CONGE', 2026, NULL, NULL, 'Congé annuel', 18.00),
        (31, 102, 'CONGE', 2022, NULL, NULL, 'Congé annuel', 18.00),
        (32, 102, 'CONGE', 2026, NULL, NULL, 'Congé annuel', 18.00)
    ) AS sc(id, id_personel, type, annee, date_du, date_au, motif, nbr_jours)
    WHERE sc.id_personel = p.legacy_id AND sc.type = 'CONGE'
);

-- Calculate RECUPERATION balance
UPDATE public.utilisateurs p
SET balance_recuperation = (
    SELECT COALESCE(SUM(sc.nbr_jours), 0)
    FROM (VALUES
        (23, 1, 'RECUPERATION', NULL, '2026-02-05', '2026-02-07', 'travail durant congé', 3.00),
        (30, 7, 'RECUPERATION', NULL, '2026-02-07', '2026-02-10', NULL, 3.00)
    ) AS sc(id, id_personel, type, annee, date_du, date_au, motif, nbr_jours)
    WHERE sc.id_personel = p.legacy_id AND sc.type = 'RECUPERATION'
);

-- Insert leave balance history
INSERT INTO public.leave_balance_history (user_id, type, amount, reason, year, date_from, date_to)
SELECT 
    p.id,
    sc.type::public.leave_request_type,
    sc.nbr_jours,
    sc.motif,
    sc.annee,
    NULLIF(sc.date_du, '')::date,
    NULLIF(sc.date_au, '')::date
FROM (VALUES
    (23, 1, 'RECUPERATION', NULL, '2026-02-05', '2026-02-07', 'travail durant congé', 3.00),
    (24, 7, 'CONGE', 2022, NULL, NULL, 'Congé annuel', 12.00),
    (25, 7, 'CONGE', 2023, NULL, NULL, 'Congé annuel', 12.00),
    (26, 7, 'CONGE', 2024, NULL, NULL, 'Congé annuel', 12.00),
    (27, 7, 'CONGE', 2025, NULL, NULL, 'Congé annuel', 12.00),
    (28, 7, 'CONGE', 2026, NULL, NULL, 'Congé annuel', 12.00),
    (29, 1, 'CONGE', 2026, NULL, NULL, 'Congé annuel', 18.00),
    (30, 7, 'RECUPERATION', NULL, '2026-02-07', '2026-02-10', NULL, 3.00),
    (31, 102, 'CONGE', 2022, NULL, NULL, 'Congé annuel', 18.00),
    (32, 102, 'CONGE', 2026, NULL, NULL, 'Congé annuel', 18.00)
) AS sc(id, id_personel, type, annee, date_du, date_au, motif, nbr_jours)
JOIN public.utilisateurs p ON p.legacy_id = sc.id_personel;

-- ==============================================================================
-- STEP 9: INSERT LEAVE REQUESTS
-- ==============================================================================

INSERT INTO public.leave_requests (
    legacy_id, user_id, request_type, start_date, end_date,
    days_count, return_date, replacement_user_id, status, balance_before
)
SELECT
    dc.id,
    (SELECT id FROM public.utilisateurs WHERE legacy_id = dc.demandeur LIMIT 1),
    CASE WHEN dc.demande = 'CONGE' THEN 'CONGE'::public.leave_request_type ELSE 'RECUPERATION'::public.leave_request_type END,
    dc.dateDu::date,
    dc.dateAu::date,
    dc.nbrJ,
    CASE WHEN dc.dateReprise = '0000-00-00' OR dc.dateReprise = '' THEN NULL ELSE dc.dateReprise::date END,
    (SELECT id FROM public.utilisateurs WHERE legacy_id = dc.interim LIMIT 1),
    map_legacy_status(dc.statut),
    dc.solde_avant
FROM (VALUES
    (17, 1, 'CONGE', 'Directeur exécutif', '2026-02-05', '2026-02-19', 11, '2026-02-20', 7, 18, 3, 21, 0, 0, '0000-00-00 00:00:00', 0, 0, '0000-00-00 00:00:00', 0, 0, '0000-00-00 00:00:00', 0, 0, '0000-00-00 00:00:00', 'Encours', 1, 0)
) AS dc(id, demandeur, demande, fonction, dateDu, dateAu, nbrJ, dateReprise, interim, droitConges, journRecup, total, validDc, idValidDc, dateValidDc, validRp, idValidRp, dateValidRp, validTg, idValidTg, dateValidTg, validDe, idValidDe, dateValidDe, statut, idCreate, solde_avant)
WHERE (SELECT id FROM public.utilisateurs WHERE legacy_id = dc.demandeur LIMIT 1) IS NOT NULL
ON CONFLICT (legacy_id) DO NOTHING;

-- ==============================================================================
-- STEP 10: VERIFICATION - CHECK WHAT WAS CREATED
-- ==============================================================================

SELECT 
    'Companies' as table_name, COUNT(*) as count FROM public.companies
UNION ALL
SELECT 'Departments', COUNT(*) FROM public.departments
UNION ALL
SELECT 'Users (Utilisateurs)', COUNT(*) FROM public.utilisateurs
UNION ALL
SELECT 'Leave Requests', COUNT(*) FROM public.leave_requests
UNION ALL
SELECT 'Leave Balance History', COUNT(*) FROM public.leave_balance_history;

-- Show user summary
SELECT 
    'Total Users' as metric,
    COUNT(*) as count
FROM public.utilisateurs
UNION ALL
SELECT 'Active Users', COUNT(*) 
FROM public.utilisateurs WHERE is_active = true
UNION ALL
SELECT 'Admins', COUNT(*) 
FROM public.utilisateurs WHERE role = 'ADMIN'
UNION ALL
SELECT 'Managers (CS)', COUNT(*) 
FROM public.utilisateurs WHERE role = 'CHEF_SERVICE'
UNION ALL
SELECT 'HR Managers (RP)', COUNT(*) 
FROM public.utilisateurs WHERE role = 'RESPONSABLE_PERSONNEL';

-- ==============================================================================
-- MIGRATION COMPLETE! 🎉
-- ==============================================================================
-- Tables created:
-- - companies (2 records)
-- - departments (16 records)
-- - utilisateurs (47 users) ← Main user table (no auth.users dependency)
-- - leave_requests (1 request)
-- - leave_balance_history (10 records)
-- - notifications, holidays, working_days, audit_logs (empty, ready to use)
-- ==============================================================================
