-- ============================================================
-- MISSION_MIGRATION.sql
-- Creates the mission_requests table for "Ordre de Mission"
-- ============================================================

-- Mission requests table
CREATE TABLE IF NOT EXISTS public.mission_requests (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Who is going on the mission
    user_id uuid REFERENCES public.utilisateurs(id) NOT NULL,

    -- Who created/assigned this mission (null = self-requested)
    assigned_by uuid REFERENCES public.utilisateurs(id),

    -- Is this self-requested or assigned?
    request_origin TEXT NOT NULL DEFAULT 'SELF',  -- 'SELF' | 'ASSIGNED'

    -- Mission scope: local (inside Morocco) or international
    mission_scope TEXT NOT NULL DEFAULT 'LOCAL',  -- 'LOCAL' | 'INTERNATIONAL'

    -- Cities
    departure_city TEXT NOT NULL,        -- Ville de départ
    arrival_city TEXT NOT NULL,           -- Ville d'arrivée / destination

    -- Mission details
    mission_object TEXT NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    days_count FLOAT NOT NULL,

    -- Transport
    transport_type TEXT,        -- 'voiture_personnelle' | 'voiture_service' | 'avion' | 'train' | 'bus' | 'autre'
    transport_details TEXT,     -- Vehicle plate, flight number, etc.

    -- Interim/replacement
    replacement_user_id uuid REFERENCES public.utilisateurs(id),

    -- Administrative
    comments TEXT,

    -- Status & Approval workflow (reuses leave_status enum)
    status public.leave_status DEFAULT 'PENDING',

    -- Supervisor opinion (Avis du superieur hierarchique direct)
    supervisor_opinion TEXT,       -- 'FAVORABLE' | 'DEFAVORABLE' | null
    supervisor_comments TEXT,
    supervisor_id uuid REFERENCES public.utilisateurs(id),
    supervisor_at TIMESTAMPTZ,

    -- Approval chain (same pattern as leave_requests)
    approved_by_dc uuid REFERENCES public.utilisateurs(id),
    approved_by_rp uuid REFERENCES public.utilisateurs(id),
    approved_by_tg uuid REFERENCES public.utilisateurs(id),
    approved_by_de uuid REFERENCES public.utilisateurs(id),
    approved_at_dc TIMESTAMPTZ,
    approved_at_rp TIMESTAMPTZ,
    approved_at_tg TIMESTAMPTZ,
    approved_at_de TIMESTAMPTZ,

    -- Executive Director decision
    director_decision TEXT,       -- 'ACCORDEE' | 'REFUSEE' | null

    -- Rejection
    rejected_by uuid REFERENCES public.utilisateurs(id),
    rejected_at TIMESTAMPTZ,
    rejection_reason TEXT,

    -- Timestamps
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_mission_requests_user ON public.mission_requests(user_id);
CREATE INDEX IF NOT EXISTS idx_mission_requests_assigned_by ON public.mission_requests(assigned_by);
CREATE INDEX IF NOT EXISTS idx_mission_requests_status ON public.mission_requests(status);
CREATE INDEX IF NOT EXISTS idx_mission_requests_dates ON public.mission_requests(start_date, end_date);

-- RLS policies
ALTER TABLE public.mission_requests ENABLE ROW LEVEL SECURITY;

-- Employees can read their own missions (requested or assigned to them)
CREATE POLICY "Users can view own missions"
    ON public.mission_requests FOR SELECT
    USING (auth.uid() = user_id OR auth.uid() = assigned_by);

-- Managers can view all missions
CREATE POLICY "Managers can view all missions"
    ON public.mission_requests FOR SELECT
    USING (
        EXISTS (
            SELECT 1 FROM public.utilisateurs
            WHERE id = auth.uid()
            AND role IN ('RH', 'CHEF_SERVICE', 'DIRECTEUR_EXECUTIF', 'ADMIN')
        )
    );

-- Users can insert their own missions
CREATE POLICY "Users can create own missions"
    ON public.mission_requests FOR INSERT
    WITH CHECK (auth.uid() = user_id);

-- Managers can insert missions on behalf of others
CREATE POLICY "Managers can create missions for others"
    ON public.mission_requests FOR INSERT
    WITH CHECK (
        EXISTS (
            SELECT 1 FROM public.utilisateurs
            WHERE id = auth.uid()
            AND role IN ('RH', 'CHEF_SERVICE', 'DIRECTEUR_EXECUTIF', 'ADMIN')
        )
    );

-- Managers can update missions (for approval workflow)
CREATE POLICY "Managers can update missions"
    ON public.mission_requests FOR UPDATE
    USING (
        EXISTS (
            SELECT 1 FROM public.utilisateurs
            WHERE id = auth.uid()
            AND role IN ('RH', 'CHEF_SERVICE', 'DIRECTEUR_EXECUTIF', 'ADMIN')
        )
    );

-- Updated_at trigger
CREATE OR REPLACE FUNCTION update_mission_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_mission_updated_at
    BEFORE UPDATE ON public.mission_requests
    FOR EACH ROW
    EXECUTE FUNCTION update_mission_updated_at();
