-- ==============================================================================
-- Phase 1: New Client Requirements — Schema Foundation
-- ==============================================================================
-- Date: 23 March 2026
-- Description: Adds all new columns, tables, indexes, and RLS policies
--              required by the new client requirements document.
--
-- Changes:
--   1. utilisateurs: superior_id (N+1), date_anciennete, annual_leave_days
--   2. leave_requests: is_derogation, derogation_approved_by
--   3. recovery_requests: mission_request_id (link to mission order)
--   4. New table: exceptional_leave_types (reference data)
--   5. New table: exceptional_leave_claims (per-employee claims)
--   6. New table: sick_leaves (3-day illness tracking)
--   7. Updated RPC: calculate_annual_entitlement (employee > dept > 18)
-- ==============================================================================

BEGIN;

-- ╔══════════════════════════════════════════════════════════════════════════════╗
-- ║  1. ALTER EXISTING TABLES                                                   ║
-- ╚══════════════════════════════════════════════════════════════════════════════╝

-- ── utilisateurs: N+1 hierarchical superior ──
ALTER TABLE public.utilisateurs
  ADD COLUMN IF NOT EXISTS superior_id UUID REFERENCES public.utilisateurs(id);

-- ── utilisateurs: seniority date (separate from hire_date) ──
ALTER TABLE public.utilisateurs
  ADD COLUMN IF NOT EXISTS date_anciennete DATE;

-- ── utilisateurs: per-employee annual leave days ──
-- NULL = inherit from department default. RH can override per employee.
ALTER TABLE public.utilisateurs
  ADD COLUMN IF NOT EXISTS annual_leave_days FLOAT;

-- ── leave_requests: derogation support ──
-- When balance is exhausted, CPA can approve a derogation that borrows from future entitlement
ALTER TABLE public.leave_requests
  ADD COLUMN IF NOT EXISTS is_derogation BOOLEAN DEFAULT false;

ALTER TABLE public.leave_requests
  ADD COLUMN IF NOT EXISTS derogation_approved_by UUID REFERENCES public.utilisateurs(id);

-- ── recovery_requests: link to mission order ──
ALTER TABLE public.recovery_requests
  ADD COLUMN IF NOT EXISTS mission_request_id BIGINT REFERENCES public.mission_requests(id);


-- ╔══════════════════════════════════════════════════════════════════════════════╗
-- ║  2. NEW TABLES                                                              ║
-- ╚══════════════════════════════════════════════════════════════════════════════╝

-- ── Exceptional leave types (reference table) ──
CREATE TABLE IF NOT EXISTS public.exceptional_leave_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    description TEXT,
    days_granted FLOAT NOT NULL DEFAULT 3,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    UNIQUE(company_id, name)
);

-- ── Exceptional leave claims (per-employee usage) ──
CREATE TABLE IF NOT EXISTS public.exceptional_leave_claims (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.utilisateurs(id) NOT NULL,
    exceptional_leave_type_id BIGINT REFERENCES public.exceptional_leave_types(id) NOT NULL,
    leave_request_id BIGINT REFERENCES public.leave_requests(id),
    claim_date DATE NOT NULL DEFAULT CURRENT_DATE,
    days_granted FLOAT NOT NULL,
    notes TEXT,
    approved_by UUID REFERENCES public.utilisateurs(id),
    approved_at TIMESTAMPTZ,
    status TEXT DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED')),
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT now() NOT NULL
);

-- ── Sick leave tracking (3 days/year authorized by ATH) ──
CREATE TABLE IF NOT EXISTS public.sick_leaves (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.utilisateurs(id) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    days_count FLOAT NOT NULL,
    reason TEXT,
    certificate_url TEXT,
    year INT NOT NULL DEFAULT EXTRACT(YEAR FROM CURRENT_DATE)::INT,
    status TEXT DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED')),
    approved_by UUID REFERENCES public.utilisateurs(id),
    approved_at TIMESTAMPTZ,
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT now() NOT NULL
);


-- ╔══════════════════════════════════════════════════════════════════════════════╗
-- ║  3. INDEXES                                                                 ║
-- ╚══════════════════════════════════════════════════════════════════════════════╝

CREATE INDEX IF NOT EXISTS idx_utilisateurs_superior
  ON public.utilisateurs(superior_id) WHERE superior_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_recovery_requests_mission
  ON public.recovery_requests(mission_request_id) WHERE mission_request_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_exceptional_leave_types_company
  ON public.exceptional_leave_types(company_id);

CREATE INDEX IF NOT EXISTS idx_exceptional_leave_claims_user
  ON public.exceptional_leave_claims(user_id);

CREATE INDEX IF NOT EXISTS idx_exceptional_leave_claims_type
  ON public.exceptional_leave_claims(exceptional_leave_type_id);

CREATE INDEX IF NOT EXISTS idx_sick_leaves_user
  ON public.sick_leaves(user_id);

CREATE INDEX IF NOT EXISTS idx_sick_leaves_year
  ON public.sick_leaves(user_id, year);


-- ╔══════════════════════════════════════════════════════════════════════════════╗
-- ║  4. RLS POLICIES                                                            ║
-- ╚══════════════════════════════════════════════════════════════════════════════╝

-- ── EXCEPTIONAL_LEAVE_TYPES (read by all, managed by RH/ADMIN) ──
ALTER TABLE public.exceptional_leave_types ENABLE ROW LEVEL SECURITY;

CREATE POLICY "exceptional_leave_types_select"
  ON public.exceptional_leave_types FOR SELECT TO authenticated USING (true);

CREATE POLICY "exceptional_leave_types_manage"
  ON public.exceptional_leave_types FOR ALL TO authenticated
  USING (public.get_my_role() IN ('RH', 'DIRECTEUR_EXECUTIF', 'ADMIN'))
  WITH CHECK (public.get_my_role() IN ('RH', 'DIRECTEUR_EXECUTIF', 'ADMIN'));

-- ── EXCEPTIONAL_LEAVE_CLAIMS ──
ALTER TABLE public.exceptional_leave_claims ENABLE ROW LEVEL SECURITY;

CREATE POLICY "exceptional_leave_claims_select"
  ON public.exceptional_leave_claims FOR SELECT TO authenticated
  USING (user_id = auth.uid() OR public.can_manage_user(user_id));

CREATE POLICY "exceptional_leave_claims_insert"
  ON public.exceptional_leave_claims FOR INSERT TO authenticated
  WITH CHECK (user_id = auth.uid() OR public.can_manage_user(user_id));

CREATE POLICY "exceptional_leave_claims_update"
  ON public.exceptional_leave_claims FOR UPDATE TO authenticated
  USING (public.can_manage_user(user_id));

-- ── SICK_LEAVES ──
ALTER TABLE public.sick_leaves ENABLE ROW LEVEL SECURITY;

CREATE POLICY "sick_leaves_select"
  ON public.sick_leaves FOR SELECT TO authenticated
  USING (user_id = auth.uid() OR public.can_manage_user(user_id));

CREATE POLICY "sick_leaves_insert"
  ON public.sick_leaves FOR INSERT TO authenticated
  WITH CHECK (user_id = auth.uid() OR public.can_manage_user(user_id));

CREATE POLICY "sick_leaves_update"
  ON public.sick_leaves FOR UPDATE TO authenticated
  USING (public.can_manage_user(user_id));


-- ╔══════════════════════════════════════════════════════════════════════════════╗
-- ║  5. GRANTS                                                                  ║
-- ╚══════════════════════════════════════════════════════════════════════════════╝

GRANT SELECT, INSERT, UPDATE, DELETE ON public.exceptional_leave_types TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.exceptional_leave_types_id_seq TO authenticated;

GRANT SELECT, INSERT, UPDATE ON public.exceptional_leave_claims TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.exceptional_leave_claims_id_seq TO authenticated;

GRANT SELECT, INSERT, UPDATE ON public.sick_leaves TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.sick_leaves_id_seq TO authenticated;


-- ╔══════════════════════════════════════════════════════════════════════════════╗
-- ║  6. UPDATED RPCs                                                            ║
-- ╚══════════════════════════════════════════════════════════════════════════════╝

-- ── calculate_annual_entitlement: simplified — employee > department > 18 ──
CREATE OR REPLACE FUNCTION calculate_annual_entitlement(p_user_id UUID)
RETURNS JSONB
LANGUAGE plpgsql
STABLE
AS $$
DECLARE
  v_user              utilisateurs%ROWTYPE;
  v_dept_days         FLOAT;
  v_seniority_date    DATE;
  v_years_of_service  FLOAT;
  v_seniority_periods INTEGER;
  v_base_days         FLOAT := 18.0;
  v_bonus_days        FLOAT := 0;
  v_total_entitlement FLOAT;
  v_max_days          FLOAT := 30.0;
  v_is_minor          BOOLEAN := false;
  v_source            TEXT := 'default';
BEGIN
  SELECT * INTO v_user FROM utilisateurs WHERE id = p_user_id;
  IF NOT FOUND THEN RAISE EXCEPTION 'User % not found', p_user_id; END IF;

  -- Simple priority: employee override > department default > 18
  IF v_user.annual_leave_days IS NOT NULL THEN
    v_base_days := v_user.annual_leave_days;
    v_source := 'employee';
  ELSIF v_user.department_id IS NOT NULL THEN
    SELECT annual_leave_days INTO v_dept_days
    FROM departments WHERE id = v_user.department_id;
    IF FOUND AND v_dept_days IS NOT NULL THEN
      v_base_days := v_dept_days;
      v_source := 'department';
    END IF;
  END IF;

  -- Use date_anciennete for seniority calc, fallback to hire_date
  v_seniority_date := COALESCE(v_user.date_anciennete, v_user.hire_date, CURRENT_DATE);

  IF v_user.birth_date IS NOT NULL THEN
    v_is_minor := (age(CURRENT_DATE, v_user.birth_date) < interval '18 years');
  END IF;
  IF v_is_minor THEN v_base_days := GREATEST(v_base_days, 24.0); END IF;

  v_years_of_service := EXTRACT(EPOCH FROM age(CURRENT_DATE, v_seniority_date)) / (365.25 * 86400);
  v_seniority_periods := FLOOR(v_years_of_service / 5.0)::INTEGER;
  v_bonus_days := v_seniority_periods * 1.5;
  v_total_entitlement := LEAST(v_base_days + v_bonus_days, v_max_days);

  RETURN jsonb_build_object(
    'user_id', p_user_id,
    'seniority_date', v_seniority_date,
    'hire_date', v_user.hire_date,
    'date_anciennete', v_user.date_anciennete,
    'annual_leave_days', v_user.annual_leave_days,
    'years_of_service', ROUND(v_years_of_service::NUMERIC, 1),
    'seniority_periods', v_seniority_periods,
    'base_days', v_base_days,
    'bonus_days', v_bonus_days,
    'annual_entitlement', v_total_entitlement,
    'is_minor', v_is_minor,
    'max_days', v_max_days,
    'department_id', v_user.department_id,
    'entitlement_source', v_source
  );
END;
$$;


-- ╔══════════════════════════════════════════════════════════════════════════════╗
-- ║  7. SEED DATA — Default exceptional leave types                             ║
-- ╚══════════════════════════════════════════════════════════════════════════════╝

DO $$
DECLARE
  v_company RECORD;
BEGIN
  FOR v_company IN SELECT id FROM public.companies LOOP
    INSERT INTO public.exceptional_leave_types (company_id, name, description, days_granted)
    VALUES
      (v_company.id, 'Mariage du salarie',        'Mariage du salarie',                          3),
      (v_company.id, 'Mariage d''un enfant',       'Mariage d''un enfant du salarie',             3),
      (v_company.id, 'Naissance',                  'Naissance d''un enfant',                      3),
      (v_company.id, 'Deces du conjoint',          'Deces du conjoint',                           3),
      (v_company.id, 'Deces d''un enfant',         'Deces d''un enfant du salarie',               3),
      (v_company.id, 'Deces d''un parent',         'Deces pere, mere, frere, soeur',              3),
      (v_company.id, 'Circoncision',               'Circoncision d''un enfant',                   3),
      (v_company.id, 'Operation du conjoint',      'Operation chirurgicale du conjoint ou enfant', 3)
    ON CONFLICT (company_id, name) DO NOTHING;
  END LOOP;
END;
$$;


COMMIT;
