-- ==============================================================================
-- Migration: Mission Pipeline Expansion
-- Date: 2026-03-26
-- Description: Adds geographic zones, personnel categories for missions,
--              tariff grid (per-diem rates), financial tracking, vehicle
--              details, and extra expenses to the mission pipeline.
--
-- Changes:
--   1. New table: mission_personnel_categories (4-tier system for per-diem)
--   2. New table: mission_zones (geographic zones, company-scoped)
--   3. New table: mission_tariff_grid (rate matrix: category x zone)
--   4. ALTER mission_requests: 18 new columns (financial, vehicle, etc.)
--   5. RLS policies for all new tables
--   6. Indexes, grants, seed data
-- ==============================================================================

BEGIN;

-- ╔══════════════════════════════════════════════════════════════════════════════╗
-- ║  1. NEW TABLES                                                             ║
-- ╚══════════════════════════════════════════════════════════════════════════════╝

-- ── Mission Personnel Categories ──
-- Separate from personnel_categories (which is for leave entitlement).
-- These 4 tiers drive per-diem rates in the tariff grid.

CREATE TABLE IF NOT EXISTS public.mission_personnel_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    description TEXT,
    sort_order INT NOT NULL DEFAULT 0,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    UNIQUE(company_id, name)
);

-- ── Mission Zones ──
-- Geographic zones for international missions (e.g., Europe/Maghreb, USA/UK).

CREATE TABLE IF NOT EXISTS public.mission_zones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    description TEXT,
    sort_order INT NOT NULL DEFAULT 0,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    UNIQUE(company_id, name)
);

-- ── Mission Tariff Grid ──
-- Rate matrix: one row per (category, zone) pair.
-- Drives per-diem calculation based on employee category + destination zone + PEC.

CREATE TABLE IF NOT EXISTS public.mission_tariff_grid (
    category_id BIGINT NOT NULL REFERENCES public.mission_personnel_categories(id) ON DELETE CASCADE,
    zone_id BIGINT NOT NULL REFERENCES public.mission_zones(id) ON DELETE CASCADE,
    petit_dej NUMERIC(10,2) NOT NULL DEFAULT 0,
    dej NUMERIC(10,2) NOT NULL DEFAULT 0,
    diner NUMERIC(10,2) NOT NULL DEFAULT 0,
    indem_avec_pec NUMERIC(10,2) NOT NULL DEFAULT 0,
    indem_sans_pec NUMERIC(10,2) NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    PRIMARY KEY (category_id, zone_id)
);


-- ╔══════════════════════════════════════════════════════════════════════════════╗
-- ║  2. ALTER utilisateurs (mission category is a profile attribute)           ║
-- ╚══════════════════════════════════════════════════════════════════════════════╝

ALTER TABLE public.utilisateurs
  ADD COLUMN IF NOT EXISTS mission_category_id BIGINT REFERENCES public.mission_personnel_categories(id);

CREATE INDEX IF NOT EXISTS idx_utilisateurs_mission_category
  ON public.utilisateurs(mission_category_id) WHERE mission_category_id IS NOT NULL;


-- ╔══════════════════════════════════════════════════════════════════════════════╗
-- ║  3. ALTER mission_requests                                                 ║
-- ╚══════════════════════════════════════════════════════════════════════════════╝

-- Snapshot of user's category at time of request (auto-populated from user profile)
ALTER TABLE public.mission_requests
  ADD COLUMN IF NOT EXISTS mission_category_id BIGINT REFERENCES public.mission_personnel_categories(id);

ALTER TABLE public.mission_requests
  ADD COLUMN IF NOT EXISTS mission_zone_id BIGINT REFERENCES public.mission_zones(id);

ALTER TABLE public.mission_requests
  ADD COLUMN IF NOT EXISTS country TEXT;

ALTER TABLE public.mission_requests
  ADD COLUMN IF NOT EXISTS venue TEXT;

ALTER TABLE public.mission_requests
  ADD COLUMN IF NOT EXISTS currency TEXT DEFAULT 'MAD';

-- Financial: PEC and breakfast
ALTER TABLE public.mission_requests
  ADD COLUMN IF NOT EXISTS pec BOOLEAN DEFAULT false;

ALTER TABLE public.mission_requests
  ADD COLUMN IF NOT EXISTS petit_dej_included BOOLEAN DEFAULT false;

-- Meal counts
ALTER TABLE public.mission_requests
  ADD COLUMN IF NOT EXISTS nbr_petit_dej INT DEFAULT 0;

ALTER TABLE public.mission_requests
  ADD COLUMN IF NOT EXISTS nbr_dej INT DEFAULT 0;

ALTER TABLE public.mission_requests
  ADD COLUMN IF NOT EXISTS nbr_diner INT DEFAULT 0;

-- Financial: computed/stored amounts
ALTER TABLE public.mission_requests
  ADD COLUMN IF NOT EXISTS daily_allowance NUMERIC(10,2) DEFAULT 0;

ALTER TABLE public.mission_requests
  ADD COLUMN IF NOT EXISTS total_allowance NUMERIC(10,2) DEFAULT 0;

ALTER TABLE public.mission_requests
  ADD COLUMN IF NOT EXISTS hotel_amount NUMERIC(10,2) DEFAULT 0;

-- Extra expenses (flexible JSONB array of {label, amount})
ALTER TABLE public.mission_requests
  ADD COLUMN IF NOT EXISTS extra_expenses JSONB DEFAULT '[]'::jsonb;

-- Vehicle details (relevant when transport_type = 'voiture_personnelle')
ALTER TABLE public.mission_requests
  ADD COLUMN IF NOT EXISTS vehicle_brand TEXT;

ALTER TABLE public.mission_requests
  ADD COLUMN IF NOT EXISTS vehicle_fiscal_power TEXT;

ALTER TABLE public.mission_requests
  ADD COLUMN IF NOT EXISTS vehicle_plate_requested TEXT;

ALTER TABLE public.mission_requests
  ADD COLUMN IF NOT EXISTS vehicle_plate_granted TEXT;

ALTER TABLE public.mission_requests
  ADD COLUMN IF NOT EXISTS vehicle_date_from DATE;

ALTER TABLE public.mission_requests
  ADD COLUMN IF NOT EXISTS vehicle_date_to DATE;

-- People
ALTER TABLE public.mission_requests
  ADD COLUMN IF NOT EXISTS persons_transported TEXT;

ALTER TABLE public.mission_requests
  ADD COLUMN IF NOT EXISTS persons_other TEXT;


-- ╔══════════════════════════════════════════════════════════════════════════════╗
-- ║  4. INDEXES                                                                ║
-- ╚══════════════════════════════════════════════════════════════════════════════╝

CREATE INDEX IF NOT EXISTS idx_mission_personnel_categories_company
  ON public.mission_personnel_categories(company_id);

CREATE INDEX IF NOT EXISTS idx_mission_zones_company
  ON public.mission_zones(company_id);

CREATE INDEX IF NOT EXISTS idx_mission_requests_category
  ON public.mission_requests(mission_category_id)
  WHERE mission_category_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_mission_requests_zone
  ON public.mission_requests(mission_zone_id)
  WHERE mission_zone_id IS NOT NULL;


-- ╔══════════════════════════════════════════════════════════════════════════════╗
-- ║  5. RLS POLICIES                                                           ║
-- ╚══════════════════════════════════════════════════════════════════════════════╝

-- ── mission_personnel_categories ──
ALTER TABLE public.mission_personnel_categories ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE policyname = 'mission_personnel_categories_select' AND tablename = 'mission_personnel_categories'
  ) THEN
    CREATE POLICY "mission_personnel_categories_select"
      ON public.mission_personnel_categories FOR SELECT TO authenticated
      USING (
        company_id IN (
          SELECT ucr.company_id FROM user_company_roles ucr
          WHERE ucr.user_id = auth.uid() AND ucr.is_active = true
        )
        OR company_id = (SELECT company_id FROM utilisateurs WHERE id = auth.uid())
      );
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE policyname = 'mission_personnel_categories_manage' AND tablename = 'mission_personnel_categories'
  ) THEN
    CREATE POLICY "mission_personnel_categories_manage"
      ON public.mission_personnel_categories FOR ALL TO authenticated
      USING (public.get_my_role() IN ('ADMIN', 'RH', 'DIRECTEUR_EXECUTIF'))
      WITH CHECK (public.get_my_role() IN ('ADMIN', 'RH', 'DIRECTEUR_EXECUTIF'));
  END IF;
END $$;

-- ── mission_zones ──
ALTER TABLE public.mission_zones ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE policyname = 'mission_zones_select' AND tablename = 'mission_zones'
  ) THEN
    CREATE POLICY "mission_zones_select"
      ON public.mission_zones FOR SELECT TO authenticated
      USING (
        company_id IN (
          SELECT ucr.company_id FROM user_company_roles ucr
          WHERE ucr.user_id = auth.uid() AND ucr.is_active = true
        )
        OR company_id = (SELECT company_id FROM utilisateurs WHERE id = auth.uid())
      );
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE policyname = 'mission_zones_manage' AND tablename = 'mission_zones'
  ) THEN
    CREATE POLICY "mission_zones_manage"
      ON public.mission_zones FOR ALL TO authenticated
      USING (public.get_my_role() IN ('ADMIN', 'RH', 'DIRECTEUR_EXECUTIF'))
      WITH CHECK (public.get_my_role() IN ('ADMIN', 'RH', 'DIRECTEUR_EXECUTIF'));
  END IF;
END $$;

-- ── mission_tariff_grid ──
ALTER TABLE public.mission_tariff_grid ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE policyname = 'mission_tariff_grid_select' AND tablename = 'mission_tariff_grid'
  ) THEN
    CREATE POLICY "mission_tariff_grid_select"
      ON public.mission_tariff_grid FOR SELECT TO authenticated
      USING (true);
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE policyname = 'mission_tariff_grid_manage' AND tablename = 'mission_tariff_grid'
  ) THEN
    CREATE POLICY "mission_tariff_grid_manage"
      ON public.mission_tariff_grid FOR ALL TO authenticated
      USING (public.get_my_role() IN ('ADMIN', 'RH', 'DIRECTEUR_EXECUTIF'))
      WITH CHECK (public.get_my_role() IN ('ADMIN', 'RH', 'DIRECTEUR_EXECUTIF'));
  END IF;
END $$;


-- ╔══════════════════════════════════════════════════════════════════════════════╗
-- ║  6. GRANTS                                                                 ║
-- ╚══════════════════════════════════════════════════════════════════════════════╝

GRANT SELECT, INSERT, UPDATE, DELETE ON public.mission_personnel_categories TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.mission_personnel_categories_id_seq TO authenticated;

GRANT SELECT, INSERT, UPDATE, DELETE ON public.mission_zones TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.mission_zones_id_seq TO authenticated;

GRANT SELECT, INSERT, UPDATE, DELETE ON public.mission_tariff_grid TO authenticated;


-- ╔══════════════════════════════════════════════════════════════════════════════╗
-- ║  7. SEED DATA                                                              ║
-- ╚══════════════════════════════════════════════════════════════════════════════╝

-- Seed mission personnel categories for all companies
DO $$
DECLARE
  v_company RECORD;
BEGIN
  FOR v_company IN SELECT id FROM public.companies LOOP
    INSERT INTO public.mission_personnel_categories (company_id, name, description, sort_order)
    VALUES
      (v_company.id, 'Membres du Conseil d''Administration, Directeur Executif & Tresorier General',
       'Categorie 1 — Direction et conseil', 1),
      (v_company.id, 'Directeurs & Coordonnateurs des Evenements Majeurs',
       'Categorie 2 — Directeurs et coordinateurs', 2),
      (v_company.id, 'Responsables de Poles & Cadres',
       'Categorie 3 — Responsables et cadres', 3),
      (v_company.id, 'Agents et Autres',
       'Categorie 4 — Agents et personnel operationnel', 4)
    ON CONFLICT (company_id, name) DO NOTHING;
  END LOOP;
END;
$$;

-- Seed mission zones for all companies
DO $$
DECLARE
  v_company RECORD;
BEGIN
  FOR v_company IN SELECT id FROM public.companies LOOP
    INSERT INTO public.mission_zones (company_id, name, description, sort_order)
    VALUES
      (v_company.id, 'Europe - Maghreb - Afrique du Nord',
       'Zone 1 — Europe, Maghreb et Afrique du Nord', 1),
      (v_company.id, 'Afrique du Sud - USA - Middle East - UK',
       'Zone 2 — Afrique du Sud, USA, Moyen-Orient, Royaume-Uni', 2)
    ON CONFLICT (company_id, name) DO NOTHING;
  END LOOP;
END;
$$;

-- Seed tariff grid (4 categories x 2 zones = 8 rows per company)
-- Values from client's old grille_tarifaire dump
DO $$
DECLARE
  v_company RECORD;
  v_cat1 BIGINT; v_cat2 BIGINT; v_cat3 BIGINT; v_cat4 BIGINT;
  v_zone1 BIGINT; v_zone2 BIGINT;
BEGIN
  FOR v_company IN SELECT id FROM public.companies LOOP
    -- Get category IDs for this company
    SELECT id INTO v_cat1 FROM mission_personnel_categories
      WHERE company_id = v_company.id AND sort_order = 1 LIMIT 1;
    SELECT id INTO v_cat2 FROM mission_personnel_categories
      WHERE company_id = v_company.id AND sort_order = 2 LIMIT 1;
    SELECT id INTO v_cat3 FROM mission_personnel_categories
      WHERE company_id = v_company.id AND sort_order = 3 LIMIT 1;
    SELECT id INTO v_cat4 FROM mission_personnel_categories
      WHERE company_id = v_company.id AND sort_order = 4 LIMIT 1;

    -- Get zone IDs for this company
    SELECT id INTO v_zone1 FROM mission_zones
      WHERE company_id = v_company.id AND sort_order = 1 LIMIT 1;
    SELECT id INTO v_zone2 FROM mission_zones
      WHERE company_id = v_company.id AND sort_order = 2 LIMIT 1;

    -- Skip if any lookup failed
    IF v_cat1 IS NULL OR v_zone1 IS NULL THEN CONTINUE; END IF;

    -- Category 1 (Direction)
    INSERT INTO mission_tariff_grid (category_id, zone_id, petit_dej, dej, diner, indem_avec_pec, indem_sans_pec)
    VALUES
      (v_cat1, v_zone1, 20, 50, 50, 450, 150),
      (v_cat1, v_zone2, 30, 70, 70, 150, 150)
    ON CONFLICT (category_id, zone_id) DO NOTHING;

    -- Category 2 (Directeurs & Coordonnateurs)
    INSERT INTO mission_tariff_grid (category_id, zone_id, petit_dej, dej, diner, indem_avec_pec, indem_sans_pec)
    VALUES
      (v_cat2, v_zone1, 15, 40, 40, 300, 80),
      (v_cat2, v_zone2, 25, 50, 50, 350, 80)
    ON CONFLICT (category_id, zone_id) DO NOTHING;

    -- Category 3 (Responsables & Cadres)
    INSERT INTO mission_tariff_grid (category_id, zone_id, petit_dej, dej, diner, indem_avec_pec, indem_sans_pec)
    VALUES
      (v_cat3, v_zone1, 15, 25, 25, 220, 50),
      (v_cat3, v_zone2, 20, 30, 30, 250, 50)
    ON CONFLICT (category_id, zone_id) DO NOTHING;

    -- Category 4 (Agents et Autres)
    INSERT INTO mission_tariff_grid (category_id, zone_id, petit_dej, dej, diner, indem_avec_pec, indem_sans_pec)
    VALUES
      (v_cat4, v_zone1, 15, 20, 25, 150, 10),
      (v_cat4, v_zone2, 20, 30, 30, 150, 30)
    ON CONFLICT (category_id, zone_id) DO NOTHING;
  END LOOP;
END;
$$;


-- Notify PostgREST to reload schema
NOTIFY pgrst, 'reload schema';

COMMIT;
